<?xml version="1.0" encoding="utf-8"?><Database Name="s5taviacao" Class="AviacaoConhecimentoFreteBasedataclassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.50.39;Initial Catalog=s5taviacao;User ID=4t" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="s5taviacaoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AviacaoConhecimentoFrete" Member="AviacaoConhecimentoFretes">
    <Type Name="AviacaoConhecimentoFrete">
      <Column Name="pId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pGW1_FILIAL" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW1_EMISDC" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW1_CDTPDC" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGV5_DSTPDC" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW1_DTEMIS" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="pGW1_SERDC" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW1_NRDC" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW1_CDREM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_NMEMIT_REM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDERP_REM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDCERP_REM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW1_CDDEST" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_NMEMIT" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDERP" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDCERP" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW1_NRROM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW1_TPFRET" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW1_DTSAI" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="pGW1_DSESP" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW1_QTVOL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW8_SEQ" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW8_ITEM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW8_DSITEM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW8_QTDE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW8_VALOR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW8_VOLUME" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW8_PESOR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pD2_ITEM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pD2_COD" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pD2_DOC" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pD2_SERIE" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pD2_QUANT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pD2_TOTAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pD2_VALBRUT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGWU_SEQ" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGWU_CDTRP" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_NMEMIT_TRETRAN" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDTERP_TRETRAN" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGWU_NRCIDD" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU7_NMCID" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU7_CDUF" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGWF_NRCALC" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGWF_TRANSP" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_NMEMIT_CALCTRP" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDTERP_CALCTRP" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGWF_EMIREM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_NMEMIT_CALCREM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDERP_CALCREM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDCERP_CALCREM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGWF_EMIDES" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_NMEMIT_CALCDES" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDERP_CALCDES" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDCERP_CALCDES" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGWF_EMIRED" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_NMEMIT_CALCRED" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDTERP_CALCRED" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGWF_EMIPAG" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_NMEMIT_CALCPAG" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDERP_CALCPAG" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDCERP_CALCPAG" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGWF_TPCALC" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGWF_CIDORI" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU7_NMCID_CALCCDORI" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU7_CDUF_CALCCDORI" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PGWF_CIDDES" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU7_NMCID_CALCCDDES" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU7_CDUF_CALCCDDES" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGWF_NRROM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW3_CDESP" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW3_EMISDF" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_NMEMIT_TRANS" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW3_SERDF" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW3_NRDF" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW3_DTEMIS" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="pGW3_TPDF" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW3_DTENT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="pGW3_CFOP" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW3_CDREM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_NMEMIT_DFREM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDERP_DFREM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDCERP_DFREM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW3_CDDEST" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_NMEMIT_DFDES" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDERP_DFDES" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDCERP_DFDES" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW3_VLDF" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW3_TAXAS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW3_PEDAG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW3_FRPESO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW3_FRVAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW3_PESOR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW3_VLCARG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW4_NRDC" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW4_SERDC" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW4_EMISDC" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_NMEMIT_DDFEMIS" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDERP_DDFEMIS" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDCERP_DDFEMIS" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGWN_NRROM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGWN_CDTRP" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_NMEMIT_ROMCAR" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDTERP_ROMCAR" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGWN_CDTPOP" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGV4_DSTPOP" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGWN_CDCLFR" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGUB_DSCLFR" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGWN_CDTPVC" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGWN_CDMTR" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW6_EMIFAT" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_NMEMIT_FATFRT" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGU3_CDERP_FATFRT" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pCDCERP_FATFRT" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW6_SERFAT" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW6_NRFAT" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW6_DTEMIS" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="pGW6_DTVENC" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="pGW6_VLFATU" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW6_VLDESC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW6_VLJURO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGWM_VLFRET_RTDCCAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGWM_VLFRET_RTDCFRT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGWM_VLFRET_RTDCCAR_TOTAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGWM_VLFRET_RTDCCAR_PERCRATEIO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW8_VALOR_RATEIO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW8_QTDE_RATEIO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW8_VOLUME_RATEIO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW8_PESOR_RATEIO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[_trackLastWriteTime]" Member="_trackLastWriteTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[_trackCreationTime]" Member="_trackCreationTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[_trackLastWriteUser]" Member="_trackLastWriteUser" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="[_trackCreationUser]" Member="_trackCreationUser" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="pGW8_CFOP" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pREGIAO_ORIGEM" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pREGIAO_DESTINO" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW8_VALOR_BRUTO_RATEIO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW1_DTEMIS_DIA" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW1_DTEMIS_MES" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW1_DTEMIS_ANO" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW1_DTSAI_DIA" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW1_DTSAI_MES" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW1_DTSAI_ANO" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW3_DTEMIS_DIA" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW3_DTEMIS_MES" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW3_DTEMIS_ANO" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW3_DTENT_DIA" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW3_DTENT_MES" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW3_DTENT_ANO" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW6_DTEMIS_DIA" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW6_DTEMIS_MES" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW6_DTEMIS_ANO" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW6_DTVENC_DIA" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW6_DTVENC_MES" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW6_DTVENC_ANO" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="pGW8_VALOR_TOTAL_NOTA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pGW8_VALOR_BRUTO_TOTAL_NOTA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pF2_PBRUTO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pF2_PLIQUI" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>