'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CodeFluent.Runtime
Imports CodeFluent.Runtime.Utilities

Namespace S5T
    
    'CodeFluent Entities generated (http://www.softfluent.com). Date: .
    <System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.01234.05678"),  _
     System.SerializableAttribute(),  _
     System.ComponentModel.DataObjectAttribute(),  _
     System.Diagnostics.DebuggerDisplayAttribute("EK={EntityKey}, pPLACA={pPLACA}, pId={pId}"),  _
     System.ComponentModel.TypeConverterAttribute(GetType(CodeFluent.Runtime.Design.NameTypeConverter))>  _
    Partial Public Class AviacaoCaminhao
        Implements System.ICloneable, System.IComparable, System.IComparable(Of S5T.AviacaoCaminhao), CodeFluent.Runtime.ICodeFluentCollectionEntity(Of Long), System.ComponentModel.IDataErrorInfo, CodeFluent.Runtime.ICodeFluentMemberValidator, CodeFluent.Runtime.ICodeFluentSummaryValidator, System.IEquatable(Of S5T.AviacaoCaminhao)
        
        Private _raisePropertyChangedEvents As Boolean = true
        
        Private _entityState As CodeFluent.Runtime.CodeFluentEntityState
        
        Private _pId As Long = -1
        
        Private _pPLACA As String = CType(Nothing, String)
        
        Private _pTIPO As String = CType(Nothing, String)
        
        Private _pDESC_VEICULO As String = CType(Nothing, String)
        
        Private _pCAPACIDADE_TON As Decimal = CodeFluentPersistence.DefaultDecimalValue
        
        Private _pCAPACIDADE_PALETE As Decimal = CodeFluentPersistence.DefaultDecimalValue
        
        <System.NonSerializedAttribute()>  _
        Private _oAviacaoViagemMovs As S5T.AviacaoViagemMovCollection
        
        Private _oAviacaoMotoristapId As Long = -1
        
        <System.NonSerializedAttribute()>  _
        Private _oAviacaoMotorista As S5T.AviacaoMotorista = Nothing
        
        Private _sStatus As S5T.Status = S5T.Status.Ativo
        
        <System.NonSerializedAttribute()>  _
        Private _oControleViagensAg As S5T.ControleViagemAgCollection
        
        Public Sub New()
            MyBase.New
            Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created
        End Sub
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Overridable Property RaisePropertyChangedEvents() As Boolean
            Get
                Return Me._raisePropertyChangedEvents
            End Get
            Set
                Me._raisePropertyChangedEvents = value
            End Set
        End Property
        
        Public Overridable Property EntityKey() As String Implements CodeFluent.Runtime.ICodeFluentEntity.EntityKey
            Get
                Return Me.pId.ToString
            End Get
            Set
                Me.pId = CType(ConvertUtilities.ChangeType(value, GetType(Long), -1),Long)
            End Set
        End Property
        
        Public Overridable ReadOnly Property EntityDisplayName() As String Implements CodeFluent.Runtime.ICodeFluentEntity.EntityDisplayName
            Get
                Return Me.pPLACA
            End Get
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(-1,Long)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Long)),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property pId() As Long
            Get
                Return Me._pId
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of Long).Default.Equals(value, Me._pId) = true) Then
                    Return
                End If
                Dim oldKey As Long = Me._pId
                Me._pId = value
                Try 
                    Me.OnCollectionKeyChanged(oldKey)
                Catch __exception As System.ArgumentException
                    Me._pId = oldKey
                    Return
                End Try
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pId"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pPLACA() As String
            Get
                Return Me._pPLACA
            End Get
            Set
                Me._pPLACA = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pPLACA"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pTIPO() As String
            Get
                Return Me._pTIPO
            End Get
            Set
                Me._pTIPO = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pTIPO"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pDESC_VEICULO() As String
            Get
                Return Me._pDESC_VEICULO
            End Get
            Set
                Me._pDESC_VEICULO = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pDESC_VEICULO"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Decimal))>  _
        Public Property pCAPACIDADE_TON() As Decimal
            Get
                Return Me._pCAPACIDADE_TON
            End Get
            Set
                Me._pCAPACIDADE_TON = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pCAPACIDADE_TON"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Decimal))>  _
        Public Property pCAPACIDADE_PALETE() As Decimal
            Get
                Return Me._pCAPACIDADE_PALETE
            End Get
            Set
                Me._pCAPACIDADE_PALETE = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pCAPACIDADE_PALETE"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ReadOnly Property oAviacaoViagemMovs() As S5T.AviacaoViagemMovCollection
            Get
                If (Me._oAviacaoViagemMovs Is Nothing) Then
                    If ((Me.pId = -1)  _
                                OrElse (Me.EntityState.Equals(CodeFluent.Runtime.CodeFluentEntityState.Created) = true)) Then
                        Me._oAviacaoViagemMovs = New S5T.AviacaoViagemMovCollection(Nothing, Nothing, Me, Nothing, Nothing, Nothing)
                        Return Me._oAviacaoViagemMovs
                    End If
                    Me._oAviacaoViagemMovs = S5T.AviacaoViagemMovCollection.LoadByoAviacaoCaminhao(Me)
                End If
                Return Me._oAviacaoViagemMovs
            End Get
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property oAviacaoMotoristapId() As Long
            Get
                If ((Me._oAviacaoMotoristapId = -1)  _
                            AndAlso (Not (Me._oAviacaoMotorista) Is Nothing)) Then
                    Me._oAviacaoMotoristapId = Me._oAviacaoMotorista.pId
                End If
                Return Me._oAviacaoMotoristapId
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of Long).Default.Equals(value, Me.oAviacaoMotoristapId) = true) Then
                    Return
                End If
                Me._oAviacaoMotorista = Nothing
                Me._oAviacaoMotoristapId = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("oAviacaoMotorista"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("oAviacaoMotoristapId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property oAviacaoMotorista() As S5T.AviacaoMotorista
            Get
                If (Me._oAviacaoMotorista Is Nothing) Then
                    Me._oAviacaoMotorista = S5T.AviacaoMotorista.Load(Me._oAviacaoMotoristapId)
                End If
                Return Me._oAviacaoMotorista
            End Get
            Set
                Me._oAviacaoMotoristapId = -1
                Me._oAviacaoMotorista = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("oAviacaoMotorista"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("oAviacaoMotoristapId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(S5T.Status))>  _
        Public Property sStatus() As S5T.Status
            Get
                Return Me._sStatus
            End Get
            Set
                Me._sStatus = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("sStatus"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ReadOnly Property oControleViagensAg() As S5T.ControleViagemAgCollection
            Get
                If (Me._oControleViagensAg Is Nothing) Then
                    If ((Me.pId = -1)  _
                                OrElse (Me.EntityState.Equals(CodeFluent.Runtime.CodeFluentEntityState.Created) = true)) Then
                        Me._oControleViagensAg = New S5T.ControleViagemAgCollection(Me, Nothing, Nothing, Nothing)
                        Return Me._oControleViagensAg
                    End If
                    Me._oControleViagensAg = S5T.ControleViagemAgCollection.LoadByoAviacaoCaminhao(Me)
                End If
                Return Me._oControleViagensAg
            End Get
        End Property
        
        ReadOnly Property System_ComponentModel_IDataErrorInfo_Error() As String Implements System.ComponentModel.IDataErrorInfo.[Error]
            Get
                Return Me.Validate(System.Globalization.CultureInfo.CurrentCulture)
            End Get
        End Property
        
        ReadOnly Property System_ComponentModel_IDataErrorInfo_Item(ByVal columnName As String) As String Implements System.ComponentModel.IDataErrorInfo.Item
            Get
                Return CodeFluentPersistence.ValidateMember(System.Globalization.CultureInfo.CurrentCulture, Me, columnName, Nothing)
            End Get
        End Property
        
        ReadOnly Property CodeFluent_Runtime_Utilities_IKeyable_System_Int64__Key() As Long Implements CodeFluent.Runtime.Utilities.IKeyable(Of Long).Key
            Get
                Return Me.pId
            End Get
        End Property
        
        Public Overridable Property EntityState() As CodeFluent.Runtime.CodeFluentEntityState Implements CodeFluent.Runtime.ICodeFluentEntity.EntityState
            Get
                Return Me._entityState
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of CodeFluent.Runtime.CodeFluentEntityState).Default.Equals(value, Me.EntityState) = true) Then
                    Return
                End If
                If ((Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted)  _
                            AndAlso (value = CodeFluent.Runtime.CodeFluentEntityState.Modified)) Then
                    Return
                End If
                If ((Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created)  _
                            AndAlso (value = CodeFluent.Runtime.CodeFluentEntityState.Modified)) Then
                    Return
                End If
                Me._entityState = value
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("EntityState"))
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Public Event EntityAction As CodeFluent.Runtime.CodeFluentEntityActionEventHandler Implements CodeFluent.Runtime.ICodeFluentEntity.EntityAction
        
        Public Event KeyChanged As System.EventHandler(Of CodeFluent.Runtime.Utilities.KeyChangedEventArgs(Of Long)) Implements CodeFluent.Runtime.Utilities.IKeyable(Of Long).KeyChanged
        
        Protected Overridable Sub OnPropertyChanged(ByVal e As System.ComponentModel.PropertyChangedEventArgs)
            If (Me.RaisePropertyChangedEvents = false) Then
                Return
            End If
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, e)
            End If
        End Sub
        
        Protected Overridable Sub OnEntityAction(ByVal e As CodeFluent.Runtime.CodeFluentEntityActionEventArgs)
            If (Not (Me.EntityActionEvent) Is Nothing) Then
                RaiseEvent EntityAction(Me, e)
            End If
        End Sub
        
        Public Overloads Overridable Function Equals(ByVal aviacaoCaminhao As S5T.AviacaoCaminhao) As Boolean Implements System.IEquatable(Of S5T.AviacaoCaminhao).Equals
            If (aviacaoCaminhao Is Nothing) Then
                Return false
            End If
            If (Me.pId = -1) Then
                Return MyBase.Equals(aviacaoCaminhao)
            End If
            Return (Me.pId.Equals(aviacaoCaminhao.pId) = true)
        End Function
        
        Public Overloads Overrides Function GetHashCode() As Integer
            Return Me.pId.GetHashCode
        End Function
        
        Public Overloads Overrides Function Equals(ByVal obj As Object) As Boolean
            Dim aviacaoCaminhao As S5T.AviacaoCaminhao = Nothing
            Try 
                aviacaoCaminhao = CType(obj,S5T.AviacaoCaminhao)
            Catch icex As System.InvalidCastException
                aviacaoCaminhao = Nothing
            End Try
            Return Me.Equals(aviacaoCaminhao)
        End Function
        
        Overridable Function System_IComparable_CompareTo(ByVal value As Object) As Integer Implements System.IComparable.CompareTo
            Dim aviacaoCaminhao As S5T.AviacaoCaminhao = Nothing
            Try 
                aviacaoCaminhao = CType(value,S5T.AviacaoCaminhao)
            Catch icex As System.InvalidCastException
                aviacaoCaminhao = Nothing
            End Try
            If (aviacaoCaminhao Is Nothing) Then
                Throw New System.ArgumentException("value")
            End If
            Dim localCompareTo As Integer = Me.CompareTo(aviacaoCaminhao)
            Return localCompareTo
        End Function
        
        Public Overridable Function CompareTo(ByVal aviacaoCaminhao As S5T.AviacaoCaminhao) As Integer Implements System.IComparable(Of S5T.AviacaoCaminhao).CompareTo
            If (aviacaoCaminhao Is Nothing) Then
                Throw New System.ArgumentNullException("aviacaoCaminhao")
            End If
            Dim localCompareTo As Integer = Me.pId.CompareTo(aviacaoCaminhao.pId)
            Return localCompareTo
        End Function
        
        Public Overloads Overridable Function Validate(ByVal culture As System.Globalization.CultureInfo) As String
            Return CodeFluentPersistence.Validate(culture, Me, Nothing)
        End Function
        
        Public Overloads Overridable Sub Validate(ByVal culture As System.Globalization.CultureInfo, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException)) Implements CodeFluent.Runtime.ICodeFluentSummaryValidator.Validate
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Validating, true, results)
            evt.Culture = culture
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Dim externalValidate As String
                If (Not (evt.Argument) Is Nothing) Then
                    externalValidate = evt.Argument.ToString
                Else
                    externalValidate = S5T.Resources.Manager.GetStringWithDefault(culture, "S5T.AviacaoCaminhao.ExternalValidate", "Type 'S5T.AviacaoCaminhao' cannot be validated.", Nothing)
                End If
                CodeFluentPersistence.AddValidationError(results, externalValidate)
            End If
            CodeFluentPersistence.ValidateMember(culture, results, Me, Nothing)
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Validated, false, results))
        End Sub
        
        Public Overloads Sub Validate()
            Dim var As String = Me.Validate(System.Globalization.CultureInfo.CurrentCulture)
            If (Not (var) Is Nothing) Then
                Throw New CodeFluent.Runtime.CodeFluentValidationException(var)
            End If
        End Sub
        
        Function CodeFluent_Runtime_ICodeFluentValidator_Validate(ByVal culture As System.Globalization.CultureInfo) As String Implements CodeFluent.Runtime.ICodeFluentValidator.Validate
            Dim localValidate As String = Me.Validate(culture)
            Return localValidate
        End Function
        
        Sub CodeFluent_Runtime_ICodeFluentMemberValidator_Validate(ByVal culture As System.Globalization.CultureInfo, ByVal memberName As String, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException)) Implements CodeFluent.Runtime.ICodeFluentMemberValidator.Validate
            Me.ValidateMember(culture, memberName, results)
        End Sub
        
        Public Overloads Overridable Function Delete() As Boolean Implements CodeFluent.Runtime.ICodeFluentEntity.Delete
            Dim ret As Boolean = false
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Deleting, true)
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Return ret
            End If
            If (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted) Then
                Return ret
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "AviacaoCaminhao", "Delete")
            persistence.AddParameter("@pId", Me.pId, CType(-1,Long))
            persistence.ExecuteNonQuery
            Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Deleted, false, false))
            ret = true
            Return ret
        End Function
        
        Protected Overridable Sub ReadRecord(ByVal reader As System.Data.IDataReader, ByVal options As CodeFluent.Runtime.CodeFluentReloadOptions)
            If (reader Is Nothing) Then
                Throw New System.ArgumentNullException("reader")
            End If
            If (((options And CodeFluent.Runtime.CodeFluentReloadOptions.Properties)  _
                        = 0)  _
                        = false) Then
                Me._pId = CodeFluentPersistence.GetReaderValue(reader, "pId", CType(-1,Long))
                Me._pPLACA = CodeFluentPersistence.GetReaderValue(reader, "pPLACA", CType(CType(Nothing, String),String))
                Me._pTIPO = CodeFluentPersistence.GetReaderValue(reader, "pTIPO", CType(CType(Nothing, String),String))
                Me._pDESC_VEICULO = CodeFluentPersistence.GetReaderValue(reader, "pDESC_VEICULO", CType(CType(Nothing, String),String))
                Me._pCAPACIDADE_TON = CodeFluentPersistence.GetReaderValue(reader, "pCAPACIDADE_TON", CType(CodeFluentPersistence.DefaultDecimalValue,Decimal))
                Me._pCAPACIDADE_PALETE = CodeFluentPersistence.GetReaderValue(reader, "pCAPACIDADE_PALETE", CType(CodeFluentPersistence.DefaultDecimalValue,Decimal))
                Me.oAviacaoMotoristapId = CodeFluentPersistence.GetReaderValue(reader, "oAviacaoMotorista_pId", CType(-1,Long))
                Me._sStatus = CType(CodeFluentPersistence.GetReaderValueEnum(reader, "sStatus", CType(S5T.Status.Ativo,S5T.Status)),S5T.Status)
            End If
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecord, false, false))
        End Sub
        
        Sub CodeFluent_Runtime_ICodeFluentEntity_ReadRecord(ByVal reader As System.Data.IDataReader) Implements CodeFluent.Runtime.ICodeFluentEntity.ReadRecord
            Me.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
        End Sub
        
        Protected Overridable Sub ReadRecordOnSave(ByVal reader As System.Data.IDataReader)
            If (reader Is Nothing) Then
                Throw New System.ArgumentNullException("reader")
            End If
            Me._pId = CodeFluentPersistence.GetReaderValue(reader, "pId", CType(-1,Long))
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecordOnSave, false, false))
        End Sub
        
        Sub CodeFluent_Runtime_ICodeFluentEntity_ReadRecordOnSave(ByVal reader As System.Data.IDataReader) Implements CodeFluent.Runtime.ICodeFluentEntity.ReadRecordOnSave
            Me.ReadRecordOnSave(reader)
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Shared Function Load(ByVal pId As Long) As S5T.AviacaoCaminhao
            If (pId = -1) Then
                Return Nothing
            End If
            Dim aviacaoCaminhao As S5T.AviacaoCaminhao = New S5T.AviacaoCaminhao()
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "AviacaoCaminhao", "Load")
            persistence.AddParameter("@pId", pId, CType(-1,Long))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    aviacaoCaminhao.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
                    aviacaoCaminhao.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    Return aviacaoCaminhao
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return Nothing
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], false)>  _
        Public Shared Function LoadBypId(ByVal pId As Long) As S5T.AviacaoCaminhao
            If (pId = -1) Then
                Return Nothing
            End If
            Dim aviacaoCaminhao As S5T.AviacaoCaminhao = New S5T.AviacaoCaminhao()
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "AviacaoCaminhao", "LoadBypId")
            persistence.AddParameter("@pId", pId, CType(-1,Long))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    aviacaoCaminhao.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
                    aviacaoCaminhao.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    Return aviacaoCaminhao
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return Nothing
        End Function
        
        Public Overridable Function Reload(ByVal options As CodeFluent.Runtime.CodeFluentReloadOptions) As Boolean
            Dim ret As Boolean = false
            If (Me.pId = -1) Then
                Return ret
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "AviacaoCaminhao", "Load")
            persistence.AddParameter("@pId", Me.pId, CType(-1,Long))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    Me.ReadRecord(reader, options)
                    Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    ret = true
                Else
                    Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return ret
        End Function
        
        Protected Overridable Function BaseSave(ByVal force As Boolean) As Boolean
            If (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted) Then
                S5T.AviacaoCaminhao.Delete(Me)
                Return false
            End If
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Saving, true)
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Return false
            End If
            CodeFluentPersistence.ThrowIfDeleted(Me)
            Me.Validate
            If ((force = false)  _
                        AndAlso (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged)) Then
                Return false
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "AviacaoCaminhao", "Save")
            persistence.AddParameter("@pId", Me.pId, CType(-1,Long))
            persistence.AddParameter("@pPLACA", Me.pPLACA, CType(Nothing, String))
            persistence.AddParameter("@pTIPO", Me.pTIPO, CType(Nothing, String))
            persistence.AddParameter("@pDESC_VEICULO", Me.pDESC_VEICULO, CType(Nothing, String))
            persistence.AddParameter("@pCAPACIDADE_TON", Me.pCAPACIDADE_TON, CodeFluentPersistence.DefaultDecimalValue)
            persistence.AddParameter("@pCAPACIDADE_PALETE", Me.pCAPACIDADE_PALETE, CodeFluentPersistence.DefaultDecimalValue)
            persistence.AddParameter("@oAviacaoMotorista_pId", Me.oAviacaoMotoristapId, CType(-1,Long))
            persistence.AddParameterEnumInt32("@sStatus", Me.sStatus, S5T.Status.Ativo)
            persistence.AddParameter("@_trackLastWriteUser", persistence.Context.User.Name)
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    Me.ReadRecordOnSave(reader)
                End If
                CodeFluentPersistence.NextResults(reader)
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Saved, false, false))
            Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
            Return true
        End Function
        
        Public Overloads Overridable Function Save() As Boolean Implements CodeFluent.Runtime.ICodeFluentEntity.Save
            Dim localSave As Boolean = Me.BaseSave(false)
            Return localSave
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)>  _
        Public Overloads Shared Function Save(ByVal aviacaoCaminhao As S5T.AviacaoCaminhao) As Boolean
            If (aviacaoCaminhao Is Nothing) Then
                Return false
            End If
            Dim ret As Boolean = aviacaoCaminhao.Save
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)>  _
        Public Shared Function Insert(ByVal aviacaoCaminhao As S5T.AviacaoCaminhao) As Boolean
            Dim ret As Boolean = S5T.AviacaoCaminhao.Save(aviacaoCaminhao)
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)>  _
        Public Overloads Shared Function Delete(ByVal aviacaoCaminhao As S5T.AviacaoCaminhao) As Boolean
            If (aviacaoCaminhao Is Nothing) Then
                Return false
            End If
            Dim ret As Boolean = aviacaoCaminhao.Delete
            Return ret
        End Function
        
        Public Function Trace() As String
            Dim stringBuilder As System.Text.StringBuilder = New System.Text.StringBuilder()
            Dim stringWriter As System.IO.StringWriter = New System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture)
            Dim writer As System.CodeDom.Compiler.IndentedTextWriter = New System.CodeDom.Compiler.IndentedTextWriter(stringWriter)
            Me.BaseTrace(writer)
            writer.Flush
            CType(writer,System.IDisposable).Dispose
            CType(stringWriter,System.IDisposable).Dispose
            Dim sr As String = stringBuilder.ToString
            Return sr
        End Function
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Sub CodeFluent_Runtime_ICodeFluentObject_Trace(ByVal writer As System.CodeDom.Compiler.IndentedTextWriter) Implements CodeFluent.Runtime.ICodeFluentObject.Trace
            Me.BaseTrace(writer)
        End Sub
        
        Protected Overridable Sub BaseTrace(ByVal writer As System.CodeDom.Compiler.IndentedTextWriter)
            writer.Write("[")
            writer.Write("pId=")
            writer.Write(Me.pId)
            writer.Write(",")
            writer.Write("pPLACA=")
            writer.Write(Me.pPLACA)
            writer.Write(",")
            writer.Write("pTIPO=")
            writer.Write(Me.pTIPO)
            writer.Write(",")
            writer.Write("pDESC_VEICULO=")
            writer.Write(Me.pDESC_VEICULO)
            writer.Write(",")
            writer.Write("pCAPACIDADE_TON=")
            writer.Write(Me.pCAPACIDADE_TON)
            writer.Write(",")
            writer.Write("pCAPACIDADE_PALETE=")
            writer.Write(Me.pCAPACIDADE_PALETE)
            writer.Write(",")
            writer.Write("oAviacaoViagemMovs=")
            If (Not (Me._oAviacaoViagemMovs) Is Nothing) Then
                CType(Me._oAviacaoViagemMovs,CodeFluent.Runtime.ICodeFluentObject).Trace(writer)
            Else
                writer.Write("<null>")
            End If
            writer.Write(",")
            writer.Write("oAviacaoMotorista=")
            If (Not (Me._oAviacaoMotorista) Is Nothing) Then
                CType(Me._oAviacaoMotorista,CodeFluent.Runtime.ICodeFluentObject).Trace(writer)
            Else
                writer.Write("<null>")
            End If
            writer.Write(",")
            writer.Write("_oAviacaoMotoristapId=")
            writer.Write(Me._oAviacaoMotoristapId)
            writer.Write(",")
            writer.Write("sStatus=")
            writer.Write(Me.sStatus)
            writer.Write(",")
            writer.Write("oControleViagensAg=")
            If (Not (Me._oControleViagensAg) Is Nothing) Then
                CType(Me._oControleViagensAg,CodeFluent.Runtime.ICodeFluentObject).Trace(writer)
            Else
                writer.Write("<null>")
            End If
            writer.Write(", EntityState=")
            writer.Write(Me.EntityState)
            writer.Write("]")
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Shared Function LoadByEntityKey(ByVal key As String) As S5T.AviacaoCaminhao
            If (key Is String.Empty) Then
                Return Nothing
            End If
            Dim aviacaoCaminhao As S5T.AviacaoCaminhao
            Dim var As Long = CType(ConvertUtilities.ChangeType(key, GetType(Long), -1),Long)
            aviacaoCaminhao = S5T.AviacaoCaminhao.Load(var)
            Return aviacaoCaminhao
        End Function
        
        Protected Overridable Sub ValidateMember(ByVal culture As System.Globalization.CultureInfo, ByVal memberName As String, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException))
        End Sub
        
        Public Overloads Function Clone(ByVal deep As Boolean) As S5T.AviacaoCaminhao
            Dim aviacaoCaminhao As S5T.AviacaoCaminhao = New S5T.AviacaoCaminhao()
            Me.CopyTo(aviacaoCaminhao, deep)
            Return aviacaoCaminhao
        End Function
        
        Public Overloads Function Clone() As S5T.AviacaoCaminhao
            Dim localClone As S5T.AviacaoCaminhao = Me.Clone(true)
            Return localClone
        End Function
        
        Function System_ICloneable_Clone() As Object Implements System.ICloneable.Clone
            Dim localClone As Object = Me.Clone
            Return localClone
        End Function
        
        Public Overridable Sub CopyFrom(ByVal dict As System.Collections.IDictionary, ByVal deep As Boolean)
            If (dict Is Nothing) Then
                Throw New System.ArgumentNullException("dict")
            End If
            If (dict.Contains("pId") = true) Then
                Me.pId = CType(ConvertUtilities.ChangeType(dict("pId"), GetType(Long), -1),Long)
            End If
            If (dict.Contains("pCAPACIDADE_TON") = true) Then
                Me.pCAPACIDADE_TON = CType(ConvertUtilities.ChangeType(dict("pCAPACIDADE_TON"), GetType(Decimal), CodeFluentPersistence.DefaultDecimalValue),Decimal)
            End If
            If (dict.Contains("pCAPACIDADE_PALETE") = true) Then
                Me.pCAPACIDADE_PALETE = CType(ConvertUtilities.ChangeType(dict("pCAPACIDADE_PALETE"), GetType(Decimal), CodeFluentPersistence.DefaultDecimalValue),Decimal)
            End If
            If (dict.Contains("sStatus") = true) Then
                Me.sStatus = CType(ConvertUtilities.ChangeType(dict("sStatus"), GetType(S5T.Status), S5T.Status.Ativo),S5T.Status)
            End If
            If (dict.Contains("pPLACA") = true) Then
                Me.pPLACA = CType(ConvertUtilities.ChangeType(dict("pPLACA"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pTIPO") = true) Then
                Me.pTIPO = CType(ConvertUtilities.ChangeType(dict("pTIPO"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pDESC_VEICULO") = true) Then
                Me.pDESC_VEICULO = CType(ConvertUtilities.ChangeType(dict("pDESC_VEICULO"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("oAviacaoMotoristapId") = true) Then
                Me.oAviacaoMotoristapId = CType(ConvertUtilities.ChangeType(dict("oAviacaoMotoristapId"), GetType(Long), -1),Long)
            End If
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyFrom, false, dict))
        End Sub
        
        Public Overloads Overridable Sub CopyTo(ByVal aviacaoCaminhao As S5T.AviacaoCaminhao, ByVal deep As Boolean)
            If (aviacaoCaminhao Is Nothing) Then
                Throw New System.ArgumentNullException("aviacaoCaminhao")
            End If
            aviacaoCaminhao.pId = Me.pId
            aviacaoCaminhao.pCAPACIDADE_TON = Me.pCAPACIDADE_TON
            aviacaoCaminhao.pCAPACIDADE_PALETE = Me.pCAPACIDADE_PALETE
            aviacaoCaminhao.sStatus = Me.sStatus
            aviacaoCaminhao.pPLACA = Me.pPLACA
            aviacaoCaminhao.pTIPO = Me.pTIPO
            aviacaoCaminhao.pDESC_VEICULO = Me.pDESC_VEICULO
            aviacaoCaminhao.oAviacaoMotoristapId = Me.oAviacaoMotoristapId
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, aviacaoCaminhao))
        End Sub
        
        Public Overloads Overridable Sub CopyTo(ByVal dict As System.Collections.IDictionary, ByVal deep As Boolean)
            If (dict Is Nothing) Then
                Throw New System.ArgumentNullException("dict")
            End If
            dict("pId") = Me.pId
            dict("pCAPACIDADE_TON") = Me.pCAPACIDADE_TON
            dict("pCAPACIDADE_PALETE") = Me.pCAPACIDADE_PALETE
            dict("sStatus") = Me.sStatus
            dict("pPLACA") = Me.pPLACA
            dict("pTIPO") = Me.pTIPO
            dict("pDESC_VEICULO") = Me.pDESC_VEICULO
            dict("oAviacaoMotoristapId") = Me.oAviacaoMotoristapId
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, dict))
        End Sub
        
        Protected Sub OnCollectionKeyChanged(ByVal key As Long)
            If (Not (Me.KeyChangedEvent) Is Nothing) Then
                RaiseEvent KeyChanged(Me, New CodeFluent.Runtime.Utilities.KeyChangedEventArgs(Of Long)(key))
            End If
        End Sub
    End Class
End Namespace
