'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CodeFluent.Runtime
Imports CodeFluent.Runtime.Utilities

Namespace S5T
    
    'CodeFluent Entities generated (http://www.softfluent.com). Date: .
    <System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.01234.05678"),  _
     System.SerializableAttribute(),  _
     System.ComponentModel.DataObjectAttribute(),  _
     System.Diagnostics.DebuggerDisplayAttribute("EK={EntityKey}, pGW1_FILIAL={pGW1_FILIAL}, pId={pId}"),  _
     System.ComponentModel.TypeConverterAttribute(GetType(CodeFluent.Runtime.Design.NameTypeConverter))>  _
    Partial Public Class AviacaoConhecimentoFreteAgrup
        Implements System.ICloneable, System.IComparable, System.IComparable(Of S5T.AviacaoConhecimentoFreteAgrup), CodeFluent.Runtime.ICodeFluentCollectionEntity(Of Long), System.ComponentModel.IDataErrorInfo, CodeFluent.Runtime.ICodeFluentMemberValidator, CodeFluent.Runtime.ICodeFluentSummaryValidator, System.IEquatable(Of S5T.AviacaoConhecimentoFreteAgrup)
        
        Private _raisePropertyChangedEvents As Boolean = true
        
        Private _entityState As CodeFluent.Runtime.CodeFluentEntityState
        
        Private _pId As Long = -1
        
        Private _pGW1_FILIAL As String = CType(Nothing, String)
        
        Private _pGW1_EMISDC As String = CType(Nothing, String)
        
        Private _pGW1_CDTPDC As String = CType(Nothing, String)
        
        Private _pGV5_DSTPDC As String = CType(Nothing, String)
        
        Private _pGW1_DTEMIS As Date = CodeFluentPersistence.DefaultDateTimeValue
        
        Private _pGW1_DTEMIS_DIA As String = CType(Nothing, String)
        
        Private _pGW1_DTEMIS_MES As String = CType(Nothing, String)
        
        Private _pGW1_DTEMIS_ANO As String = CType(Nothing, String)
        
        Private _pGW1_SERDC As String = CType(Nothing, String)
        
        Private _pGW1_NRDC As String = CType(Nothing, String)
        
        Private _pGW1_CDREM As String = CType(Nothing, String)
        
        Private _pGU3_NMEMIT_REM As String = CType(Nothing, String)
        
        Private _pGU3_CDERP_REM As String = CType(Nothing, String)
        
        Private _pGU3_CDCERP_REM As String = CType(Nothing, String)
        
        Private _pGW1_CDDEST As String = CType(Nothing, String)
        
        Private _pGU3_NMEMIT As String = CType(Nothing, String)
        
        Private _pGU3_CDERP As String = CType(Nothing, String)
        
        Private _pGU3_CDCERP As String = CType(Nothing, String)
        
        Private _pGW1_NRROM As String = CType(Nothing, String)
        
        Private _pGW1_TPFRET As String = CType(Nothing, String)
        
        Private _pGW1_DTSAI As Date = CodeFluentPersistence.DefaultDateTimeValue
        
        Private _pGW1_DTSAI_DIA As String = CType(Nothing, String)
        
        Private _pGW1_DTSAI_MES As String = CType(Nothing, String)
        
        Private _pGW1_DTSAI_ANO As String = CType(Nothing, String)
        
        Private _pGW1_DSESP As String = CType(Nothing, String)
        
        Private _pGW3_NRDF As String = CType(Nothing, String)
        
        Private _pGW1_QTVOL As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _pGW8_VALOR_TOTAL_NOTA As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _pGW8_VALOR_BRUTO_TOTAL_NOTA As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _pVALOR_TOTAL_NF_FRETE_AGRUPADO As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _pVALOR_FRETE_TOTAL As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _pPERC_NF_FRETE_AGRUPADO As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _pGWM_VLFRET_CFRT_CCAR_NOVOFRETE As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _pGWM_VLFRET_RTDCCAR_TOTALNRDC As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _pSTATUS_GFE As String = CType(Nothing, String)
        
        Private _pF2_PBRUTO_TOTALNRDC As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _pF2_PLIQUI_TOTALNRDC As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Public Sub New()
            MyBase.New
            Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created
        End Sub
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Overridable Property RaisePropertyChangedEvents() As Boolean
            Get
                Return Me._raisePropertyChangedEvents
            End Get
            Set
                Me._raisePropertyChangedEvents = value
            End Set
        End Property
        
        Public Overridable Property EntityKey() As String Implements CodeFluent.Runtime.ICodeFluentEntity.EntityKey
            Get
                Return Me.pId.ToString
            End Get
            Set
                Me.pId = CType(ConvertUtilities.ChangeType(value, GetType(Long), -1),Long)
            End Set
        End Property
        
        Public Overridable ReadOnly Property EntityDisplayName() As String Implements CodeFluent.Runtime.ICodeFluentEntity.EntityDisplayName
            Get
                Return Me.pGW1_FILIAL
            End Get
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(-1,Long)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Long)),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property pId() As Long
            Get
                Return Me._pId
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of Long).Default.Equals(value, Me._pId) = true) Then
                    Return
                End If
                Dim oldKey As Long = Me._pId
                Me._pId = value
                Try 
                    Me.OnCollectionKeyChanged(oldKey)
                Catch __exception As System.ArgumentException
                    Me._pId = oldKey
                    Return
                End Try
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pId"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGW1_FILIAL() As String
            Get
                Return Me._pGW1_FILIAL
            End Get
            Set
                Me._pGW1_FILIAL = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_FILIAL"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGW1_EMISDC() As String
            Get
                Return Me._pGW1_EMISDC
            End Get
            Set
                Me._pGW1_EMISDC = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_EMISDC"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGW1_CDTPDC() As String
            Get
                Return Me._pGW1_CDTPDC
            End Get
            Set
                Me._pGW1_CDTPDC = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_CDTPDC"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGV5_DSTPDC() As String
            Get
                Return Me._pGV5_DSTPDC
            End Get
            Set
                Me._pGV5_DSTPDC = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGV5_DSTPDC"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Date))>  _
        Public Property pGW1_DTEMIS() As Date
            Get
                Return Me._pGW1_DTEMIS
            End Get
            Set
                Me._pGW1_DTEMIS = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_DTEMIS"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGW1_DTEMIS_DIA() As String
            Get
                Return Me._pGW1_DTEMIS_DIA
            End Get
            Set
                Me._pGW1_DTEMIS_DIA = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_DTEMIS_DIA"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGW1_DTEMIS_MES() As String
            Get
                Return Me._pGW1_DTEMIS_MES
            End Get
            Set
                Me._pGW1_DTEMIS_MES = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_DTEMIS_MES"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGW1_DTEMIS_ANO() As String
            Get
                Return Me._pGW1_DTEMIS_ANO
            End Get
            Set
                Me._pGW1_DTEMIS_ANO = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_DTEMIS_ANO"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGW1_SERDC() As String
            Get
                Return Me._pGW1_SERDC
            End Get
            Set
                Me._pGW1_SERDC = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_SERDC"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGW1_NRDC() As String
            Get
                Return Me._pGW1_NRDC
            End Get
            Set
                Me._pGW1_NRDC = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_NRDC"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGW1_CDREM() As String
            Get
                Return Me._pGW1_CDREM
            End Get
            Set
                Me._pGW1_CDREM = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_CDREM"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGU3_NMEMIT_REM() As String
            Get
                Return Me._pGU3_NMEMIT_REM
            End Get
            Set
                Me._pGU3_NMEMIT_REM = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGU3_NMEMIT_REM"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGU3_CDERP_REM() As String
            Get
                Return Me._pGU3_CDERP_REM
            End Get
            Set
                Me._pGU3_CDERP_REM = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGU3_CDERP_REM"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGU3_CDCERP_REM() As String
            Get
                Return Me._pGU3_CDCERP_REM
            End Get
            Set
                Me._pGU3_CDCERP_REM = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGU3_CDCERP_REM"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGW1_CDDEST() As String
            Get
                Return Me._pGW1_CDDEST
            End Get
            Set
                Me._pGW1_CDDEST = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_CDDEST"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGU3_NMEMIT() As String
            Get
                Return Me._pGU3_NMEMIT
            End Get
            Set
                Me._pGU3_NMEMIT = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGU3_NMEMIT"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGU3_CDERP() As String
            Get
                Return Me._pGU3_CDERP
            End Get
            Set
                Me._pGU3_CDERP = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGU3_CDERP"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGU3_CDCERP() As String
            Get
                Return Me._pGU3_CDCERP
            End Get
            Set
                Me._pGU3_CDCERP = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGU3_CDCERP"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGW1_NRROM() As String
            Get
                Return Me._pGW1_NRROM
            End Get
            Set
                Me._pGW1_NRROM = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_NRROM"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGW1_TPFRET() As String
            Get
                Return Me._pGW1_TPFRET
            End Get
            Set
                Me._pGW1_TPFRET = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_TPFRET"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Date))>  _
        Public Property pGW1_DTSAI() As Date
            Get
                Return Me._pGW1_DTSAI
            End Get
            Set
                Me._pGW1_DTSAI = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_DTSAI"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGW1_DTSAI_DIA() As String
            Get
                Return Me._pGW1_DTSAI_DIA
            End Get
            Set
                Me._pGW1_DTSAI_DIA = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_DTSAI_DIA"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGW1_DTSAI_MES() As String
            Get
                Return Me._pGW1_DTSAI_MES
            End Get
            Set
                Me._pGW1_DTSAI_MES = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_DTSAI_MES"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGW1_DTSAI_ANO() As String
            Get
                Return Me._pGW1_DTSAI_ANO
            End Get
            Set
                Me._pGW1_DTSAI_ANO = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_DTSAI_ANO"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGW1_DSESP() As String
            Get
                Return Me._pGW1_DSESP
            End Get
            Set
                Me._pGW1_DSESP = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_DSESP"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pGW3_NRDF() As String
            Get
                Return Me._pGW3_NRDF
            End Get
            Set
                Me._pGW3_NRDF = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW3_NRDF"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property pGW1_QTVOL() As Double
            Get
                Return Me._pGW1_QTVOL
            End Get
            Set
                Me._pGW1_QTVOL = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW1_QTVOL"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property pGW8_VALOR_TOTAL_NOTA() As Double
            Get
                Return Me._pGW8_VALOR_TOTAL_NOTA
            End Get
            Set
                Me._pGW8_VALOR_TOTAL_NOTA = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW8_VALOR_TOTAL_NOTA"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property pGW8_VALOR_BRUTO_TOTAL_NOTA() As Double
            Get
                Return Me._pGW8_VALOR_BRUTO_TOTAL_NOTA
            End Get
            Set
                Me._pGW8_VALOR_BRUTO_TOTAL_NOTA = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGW8_VALOR_BRUTO_TOTAL_NOTA"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property pVALOR_TOTAL_NF_FRETE_AGRUPADO() As Double
            Get
                Return Me._pVALOR_TOTAL_NF_FRETE_AGRUPADO
            End Get
            Set
                Me._pVALOR_TOTAL_NF_FRETE_AGRUPADO = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pVALOR_TOTAL_NF_FRETE_AGRUPADO"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property pVALOR_FRETE_TOTAL() As Double
            Get
                Return Me._pVALOR_FRETE_TOTAL
            End Get
            Set
                Me._pVALOR_FRETE_TOTAL = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pVALOR_FRETE_TOTAL"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property pPERC_NF_FRETE_AGRUPADO() As Double
            Get
                Return Me._pPERC_NF_FRETE_AGRUPADO
            End Get
            Set
                Me._pPERC_NF_FRETE_AGRUPADO = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pPERC_NF_FRETE_AGRUPADO"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property pGWM_VLFRET_CFRT_CCAR_NOVOFRETE() As Double
            Get
                Return Me._pGWM_VLFRET_CFRT_CCAR_NOVOFRETE
            End Get
            Set
                Me._pGWM_VLFRET_CFRT_CCAR_NOVOFRETE = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGWM_VLFRET_CFRT_CCAR_NOVOFRETE"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property pGWM_VLFRET_RTDCCAR_TOTALNRDC() As Double
            Get
                Return Me._pGWM_VLFRET_RTDCCAR_TOTALNRDC
            End Get
            Set
                Me._pGWM_VLFRET_RTDCCAR_TOTALNRDC = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pGWM_VLFRET_RTDCCAR_TOTALNRDC"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pSTATUS_GFE() As String
            Get
                Return Me._pSTATUS_GFE
            End Get
            Set
                Me._pSTATUS_GFE = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pSTATUS_GFE"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property pF2_PBRUTO_TOTALNRDC() As Double
            Get
                Return Me._pF2_PBRUTO_TOTALNRDC
            End Get
            Set
                Me._pF2_PBRUTO_TOTALNRDC = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pF2_PBRUTO_TOTALNRDC"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property pF2_PLIQUI_TOTALNRDC() As Double
            Get
                Return Me._pF2_PLIQUI_TOTALNRDC
            End Get
            Set
                Me._pF2_PLIQUI_TOTALNRDC = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pF2_PLIQUI_TOTALNRDC"))
            End Set
        End Property
        
        ReadOnly Property System_ComponentModel_IDataErrorInfo_Error() As String Implements System.ComponentModel.IDataErrorInfo.[Error]
            Get
                Return Me.Validate(System.Globalization.CultureInfo.CurrentCulture)
            End Get
        End Property
        
        ReadOnly Property System_ComponentModel_IDataErrorInfo_Item(ByVal columnName As String) As String Implements System.ComponentModel.IDataErrorInfo.Item
            Get
                Return CodeFluentPersistence.ValidateMember(System.Globalization.CultureInfo.CurrentCulture, Me, columnName, Nothing)
            End Get
        End Property
        
        ReadOnly Property CodeFluent_Runtime_Utilities_IKeyable_System_Int64__Key() As Long Implements CodeFluent.Runtime.Utilities.IKeyable(Of Long).Key
            Get
                Return Me.pId
            End Get
        End Property
        
        Public Overridable Property EntityState() As CodeFluent.Runtime.CodeFluentEntityState Implements CodeFluent.Runtime.ICodeFluentEntity.EntityState
            Get
                Return Me._entityState
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of CodeFluent.Runtime.CodeFluentEntityState).Default.Equals(value, Me.EntityState) = true) Then
                    Return
                End If
                If ((Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted)  _
                            AndAlso (value = CodeFluent.Runtime.CodeFluentEntityState.Modified)) Then
                    Return
                End If
                If ((Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created)  _
                            AndAlso (value = CodeFluent.Runtime.CodeFluentEntityState.Modified)) Then
                    Return
                End If
                Me._entityState = value
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("EntityState"))
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Public Event EntityAction As CodeFluent.Runtime.CodeFluentEntityActionEventHandler Implements CodeFluent.Runtime.ICodeFluentEntity.EntityAction
        
        Public Event KeyChanged As System.EventHandler(Of CodeFluent.Runtime.Utilities.KeyChangedEventArgs(Of Long)) Implements CodeFluent.Runtime.Utilities.IKeyable(Of Long).KeyChanged
        
        Protected Overridable Sub OnPropertyChanged(ByVal e As System.ComponentModel.PropertyChangedEventArgs)
            If (Me.RaisePropertyChangedEvents = false) Then
                Return
            End If
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, e)
            End If
        End Sub
        
        Protected Overridable Sub OnEntityAction(ByVal e As CodeFluent.Runtime.CodeFluentEntityActionEventArgs)
            If (Not (Me.EntityActionEvent) Is Nothing) Then
                RaiseEvent EntityAction(Me, e)
            End If
        End Sub
        
        Public Overloads Overridable Function Equals(ByVal aviacaoConhecimentoFreteAgrup As S5T.AviacaoConhecimentoFreteAgrup) As Boolean Implements System.IEquatable(Of S5T.AviacaoConhecimentoFreteAgrup).Equals
            If (aviacaoConhecimentoFreteAgrup Is Nothing) Then
                Return false
            End If
            If (Me.pId = -1) Then
                Return MyBase.Equals(aviacaoConhecimentoFreteAgrup)
            End If
            Return (Me.pId.Equals(aviacaoConhecimentoFreteAgrup.pId) = true)
        End Function
        
        Public Overloads Overrides Function GetHashCode() As Integer
            Return Me.pId.GetHashCode
        End Function
        
        Public Overloads Overrides Function Equals(ByVal obj As Object) As Boolean
            Dim aviacaoConhecimentoFreteAgrup As S5T.AviacaoConhecimentoFreteAgrup = Nothing
            Try 
                aviacaoConhecimentoFreteAgrup = CType(obj,S5T.AviacaoConhecimentoFreteAgrup)
            Catch icex As System.InvalidCastException
                aviacaoConhecimentoFreteAgrup = Nothing
            End Try
            Return Me.Equals(aviacaoConhecimentoFreteAgrup)
        End Function
        
        Overridable Function System_IComparable_CompareTo(ByVal value As Object) As Integer Implements System.IComparable.CompareTo
            Dim aviacaoConhecimentoFreteAgrup As S5T.AviacaoConhecimentoFreteAgrup = Nothing
            Try 
                aviacaoConhecimentoFreteAgrup = CType(value,S5T.AviacaoConhecimentoFreteAgrup)
            Catch icex As System.InvalidCastException
                aviacaoConhecimentoFreteAgrup = Nothing
            End Try
            If (aviacaoConhecimentoFreteAgrup Is Nothing) Then
                Throw New System.ArgumentException("value")
            End If
            Dim localCompareTo As Integer = Me.CompareTo(aviacaoConhecimentoFreteAgrup)
            Return localCompareTo
        End Function
        
        Public Overridable Function CompareTo(ByVal aviacaoConhecimentoFreteAgrup As S5T.AviacaoConhecimentoFreteAgrup) As Integer Implements System.IComparable(Of S5T.AviacaoConhecimentoFreteAgrup).CompareTo
            If (aviacaoConhecimentoFreteAgrup Is Nothing) Then
                Throw New System.ArgumentNullException("aviacaoConhecimentoFreteAgrup")
            End If
            Dim localCompareTo As Integer = Me.pId.CompareTo(aviacaoConhecimentoFreteAgrup.pId)
            Return localCompareTo
        End Function
        
        Public Overloads Overridable Function Validate(ByVal culture As System.Globalization.CultureInfo) As String
            Return CodeFluentPersistence.Validate(culture, Me, Nothing)
        End Function
        
        Public Overloads Overridable Sub Validate(ByVal culture As System.Globalization.CultureInfo, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException)) Implements CodeFluent.Runtime.ICodeFluentSummaryValidator.Validate
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Validating, true, results)
            evt.Culture = culture
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Dim externalValidate As String
                If (Not (evt.Argument) Is Nothing) Then
                    externalValidate = evt.Argument.ToString
                Else
                    externalValidate = S5T.Resources.Manager.GetStringWithDefault(culture, "S5T.AviacaoConhecimentoFreteAgrup.ExternalValidate", "Type 'S5T.AviacaoConhecimentoFreteAgrup' cannot be validated.", Nothing)
                End If
                CodeFluentPersistence.AddValidationError(results, externalValidate)
            End If
            CodeFluentPersistence.ValidateMember(culture, results, Me, Nothing)
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Validated, false, results))
        End Sub
        
        Public Overloads Sub Validate()
            Dim var As String = Me.Validate(System.Globalization.CultureInfo.CurrentCulture)
            If (Not (var) Is Nothing) Then
                Throw New CodeFluent.Runtime.CodeFluentValidationException(var)
            End If
        End Sub
        
        Function CodeFluent_Runtime_ICodeFluentValidator_Validate(ByVal culture As System.Globalization.CultureInfo) As String Implements CodeFluent.Runtime.ICodeFluentValidator.Validate
            Dim localValidate As String = Me.Validate(culture)
            Return localValidate
        End Function
        
        Sub CodeFluent_Runtime_ICodeFluentMemberValidator_Validate(ByVal culture As System.Globalization.CultureInfo, ByVal memberName As String, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException)) Implements CodeFluent.Runtime.ICodeFluentMemberValidator.Validate
            Me.ValidateMember(culture, memberName, results)
        End Sub
        
        Public Overloads Overridable Function Delete() As Boolean Implements CodeFluent.Runtime.ICodeFluentEntity.Delete
            Dim ret As Boolean = false
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Deleting, true)
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Return ret
            End If
            If (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted) Then
                Return ret
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "AviacaoConhecimentoFreteAgrup", "Delete")
            persistence.AddParameter("@pId", Me.pId, CType(-1,Long))
            persistence.ExecuteNonQuery
            Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Deleted, false, false))
            ret = true
            Return ret
        End Function
        
        Protected Overridable Sub ReadRecord(ByVal reader As System.Data.IDataReader, ByVal options As CodeFluent.Runtime.CodeFluentReloadOptions)
            If (reader Is Nothing) Then
                Throw New System.ArgumentNullException("reader")
            End If
            If (((options And CodeFluent.Runtime.CodeFluentReloadOptions.Properties)  _
                        = 0)  _
                        = false) Then
                Me._pId = CodeFluentPersistence.GetReaderValue(reader, "pId", CType(-1,Long))
                Me._pGW1_FILIAL = CodeFluentPersistence.GetReaderValue(reader, "pGW1_FILIAL", CType(CType(Nothing, String),String))
                Me._pGW1_EMISDC = CodeFluentPersistence.GetReaderValue(reader, "pGW1_EMISDC", CType(CType(Nothing, String),String))
                Me._pGW1_CDTPDC = CodeFluentPersistence.GetReaderValue(reader, "pGW1_CDTPDC", CType(CType(Nothing, String),String))
                Me._pGV5_DSTPDC = CodeFluentPersistence.GetReaderValue(reader, "pGV5_DSTPDC", CType(CType(Nothing, String),String))
                Me._pGW1_DTEMIS = CodeFluentPersistence.GetReaderValue(reader, "pGW1_DTEMIS", CType(CodeFluentPersistence.DefaultDateTimeValue,Date))
                Me._pGW1_DTEMIS_DIA = CodeFluentPersistence.GetReaderValue(reader, "pGW1_DTEMIS_DIA", CType(CType(Nothing, String),String))
                Me._pGW1_DTEMIS_MES = CodeFluentPersistence.GetReaderValue(reader, "pGW1_DTEMIS_MES", CType(CType(Nothing, String),String))
                Me._pGW1_DTEMIS_ANO = CodeFluentPersistence.GetReaderValue(reader, "pGW1_DTEMIS_ANO", CType(CType(Nothing, String),String))
                Me._pGW1_SERDC = CodeFluentPersistence.GetReaderValue(reader, "pGW1_SERDC", CType(CType(Nothing, String),String))
                Me._pGW1_NRDC = CodeFluentPersistence.GetReaderValue(reader, "pGW1_NRDC", CType(CType(Nothing, String),String))
                Me._pGW1_CDREM = CodeFluentPersistence.GetReaderValue(reader, "pGW1_CDREM", CType(CType(Nothing, String),String))
                Me._pGU3_NMEMIT_REM = CodeFluentPersistence.GetReaderValue(reader, "pGU3_NMEMIT_REM", CType(CType(Nothing, String),String))
                Me._pGU3_CDERP_REM = CodeFluentPersistence.GetReaderValue(reader, "pGU3_CDERP_REM", CType(CType(Nothing, String),String))
                Me._pGU3_CDCERP_REM = CodeFluentPersistence.GetReaderValue(reader, "pGU3_CDCERP_REM", CType(CType(Nothing, String),String))
                Me._pGW1_CDDEST = CodeFluentPersistence.GetReaderValue(reader, "pGW1_CDDEST", CType(CType(Nothing, String),String))
                Me._pGU3_NMEMIT = CodeFluentPersistence.GetReaderValue(reader, "pGU3_NMEMIT", CType(CType(Nothing, String),String))
                Me._pGU3_CDERP = CodeFluentPersistence.GetReaderValue(reader, "pGU3_CDERP", CType(CType(Nothing, String),String))
                Me._pGU3_CDCERP = CodeFluentPersistence.GetReaderValue(reader, "pGU3_CDCERP", CType(CType(Nothing, String),String))
                Me._pGW1_NRROM = CodeFluentPersistence.GetReaderValue(reader, "pGW1_NRROM", CType(CType(Nothing, String),String))
                Me._pGW1_TPFRET = CodeFluentPersistence.GetReaderValue(reader, "pGW1_TPFRET", CType(CType(Nothing, String),String))
                Me._pGW1_DTSAI = CodeFluentPersistence.GetReaderValue(reader, "pGW1_DTSAI", CType(CodeFluentPersistence.DefaultDateTimeValue,Date))
                Me._pGW1_DTSAI_DIA = CodeFluentPersistence.GetReaderValue(reader, "pGW1_DTSAI_DIA", CType(CType(Nothing, String),String))
                Me._pGW1_DTSAI_MES = CodeFluentPersistence.GetReaderValue(reader, "pGW1_DTSAI_MES", CType(CType(Nothing, String),String))
                Me._pGW1_DTSAI_ANO = CodeFluentPersistence.GetReaderValue(reader, "pGW1_DTSAI_ANO", CType(CType(Nothing, String),String))
                Me._pGW1_DSESP = CodeFluentPersistence.GetReaderValue(reader, "pGW1_DSESP", CType(CType(Nothing, String),String))
                Me._pGW3_NRDF = CodeFluentPersistence.GetReaderValue(reader, "pGW3_NRDF", CType(CType(Nothing, String),String))
                Me._pGW1_QTVOL = CodeFluentPersistence.GetReaderValue(reader, "pGW1_QTVOL", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._pGW8_VALOR_TOTAL_NOTA = CodeFluentPersistence.GetReaderValue(reader, "pGW8_VALOR_TOTAL_NOTA", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._pGW8_VALOR_BRUTO_TOTAL_NOTA = CodeFluentPersistence.GetReaderValue(reader, "pGW8_VALOR_BRUTO_TOTAL_NOTA", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._pVALOR_TOTAL_NF_FRETE_AGRUPADO = CodeFluentPersistence.GetReaderValue(reader, "pVALOR_TOTAL_NF_FRETE_AGRUPADO", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._pVALOR_FRETE_TOTAL = CodeFluentPersistence.GetReaderValue(reader, "pVALOR_FRETE_TOTAL", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._pPERC_NF_FRETE_AGRUPADO = CodeFluentPersistence.GetReaderValue(reader, "pPERC_NF_FRETE_AGRUPADO", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._pGWM_VLFRET_CFRT_CCAR_NOVOFRETE = CodeFluentPersistence.GetReaderValue(reader, "pGWM_VLFRET_CFRT_CCAR_NOVOFRETE", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._pGWM_VLFRET_RTDCCAR_TOTALNRDC = CodeFluentPersistence.GetReaderValue(reader, "pGWM_VLFRET_RTDCCAR_TOTALNRDC", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._pSTATUS_GFE = CodeFluentPersistence.GetReaderValue(reader, "pSTATUS_GFE", CType(CType(Nothing, String),String))
                Me._pF2_PBRUTO_TOTALNRDC = CodeFluentPersistence.GetReaderValue(reader, "pF2_PBRUTO_TOTALNRDC", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._pF2_PLIQUI_TOTALNRDC = CodeFluentPersistence.GetReaderValue(reader, "pF2_PLIQUI_TOTALNRDC", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
            End If
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecord, false, false))
        End Sub
        
        Sub CodeFluent_Runtime_ICodeFluentEntity_ReadRecord(ByVal reader As System.Data.IDataReader) Implements CodeFluent.Runtime.ICodeFluentEntity.ReadRecord
            Me.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
        End Sub
        
        Protected Overridable Sub ReadRecordOnSave(ByVal reader As System.Data.IDataReader)
            If (reader Is Nothing) Then
                Throw New System.ArgumentNullException("reader")
            End If
            Me._pId = CodeFluentPersistence.GetReaderValue(reader, "pId", CType(-1,Long))
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecordOnSave, false, false))
        End Sub
        
        Sub CodeFluent_Runtime_ICodeFluentEntity_ReadRecordOnSave(ByVal reader As System.Data.IDataReader) Implements CodeFluent.Runtime.ICodeFluentEntity.ReadRecordOnSave
            Me.ReadRecordOnSave(reader)
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Shared Function Load(ByVal pId As Long) As S5T.AviacaoConhecimentoFreteAgrup
            If (pId = -1) Then
                Return Nothing
            End If
            Dim aviacaoConhecimentoFreteAgrup As S5T.AviacaoConhecimentoFreteAgrup = New S5T.AviacaoConhecimentoFreteAgrup()
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "AviacaoConhecimentoFreteAgrup", "Load")
            persistence.AddParameter("@pId", pId, CType(-1,Long))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    aviacaoConhecimentoFreteAgrup.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
                    aviacaoConhecimentoFreteAgrup.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    Return aviacaoConhecimentoFreteAgrup
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return Nothing
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], false)>  _
        Public Shared Function LoadBypId(ByVal pId As Long) As S5T.AviacaoConhecimentoFreteAgrup
            If (pId = -1) Then
                Return Nothing
            End If
            Dim aviacaoConhecimentoFreteAgrup As S5T.AviacaoConhecimentoFreteAgrup = New S5T.AviacaoConhecimentoFreteAgrup()
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "AviacaoConhecimentoFreteAgrup", "LoadBypId")
            persistence.AddParameter("@pId", pId, CType(-1,Long))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    aviacaoConhecimentoFreteAgrup.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
                    aviacaoConhecimentoFreteAgrup.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    Return aviacaoConhecimentoFreteAgrup
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return Nothing
        End Function
        
        Public Overridable Function Reload(ByVal options As CodeFluent.Runtime.CodeFluentReloadOptions) As Boolean
            Dim ret As Boolean = false
            If (Me.pId = -1) Then
                Return ret
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "AviacaoConhecimentoFreteAgrup", "Load")
            persistence.AddParameter("@pId", Me.pId, CType(-1,Long))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    Me.ReadRecord(reader, options)
                    Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    ret = true
                Else
                    Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return ret
        End Function
        
        Protected Overridable Function BaseSave(ByVal force As Boolean) As Boolean
            If (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted) Then
                S5T.AviacaoConhecimentoFreteAgrup.Delete(Me)
                Return false
            End If
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Saving, true)
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Return false
            End If
            CodeFluentPersistence.ThrowIfDeleted(Me)
            Me.Validate
            If ((force = false)  _
                        AndAlso (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged)) Then
                Return false
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "AviacaoConhecimentoFreteAgrup", "Save")
            persistence.AddParameter("@pId", Me.pId, CType(-1,Long))
            persistence.AddParameter("@pGW1_FILIAL", Me.pGW1_FILIAL, CType(Nothing, String))
            persistence.AddParameter("@pGW1_EMISDC", Me.pGW1_EMISDC, CType(Nothing, String))
            persistence.AddParameter("@pGW1_CDTPDC", Me.pGW1_CDTPDC, CType(Nothing, String))
            persistence.AddParameter("@pGV5_DSTPDC", Me.pGV5_DSTPDC, CType(Nothing, String))
            persistence.AddParameter("@pGW1_DTEMIS", Me.pGW1_DTEMIS, CodeFluentPersistence.DefaultDateTimeValue)
            persistence.AddParameter("@pGW1_DTEMIS_DIA", Me.pGW1_DTEMIS_DIA, CType(Nothing, String))
            persistence.AddParameter("@pGW1_DTEMIS_MES", Me.pGW1_DTEMIS_MES, CType(Nothing, String))
            persistence.AddParameter("@pGW1_DTEMIS_ANO", Me.pGW1_DTEMIS_ANO, CType(Nothing, String))
            persistence.AddParameter("@pGW1_SERDC", Me.pGW1_SERDC, CType(Nothing, String))
            persistence.AddParameter("@pGW1_NRDC", Me.pGW1_NRDC, CType(Nothing, String))
            persistence.AddParameter("@pGW1_CDREM", Me.pGW1_CDREM, CType(Nothing, String))
            persistence.AddParameter("@pGU3_NMEMIT_REM", Me.pGU3_NMEMIT_REM, CType(Nothing, String))
            persistence.AddParameter("@pGU3_CDERP_REM", Me.pGU3_CDERP_REM, CType(Nothing, String))
            persistence.AddParameter("@pGU3_CDCERP_REM", Me.pGU3_CDCERP_REM, CType(Nothing, String))
            persistence.AddParameter("@pGW1_CDDEST", Me.pGW1_CDDEST, CType(Nothing, String))
            persistence.AddParameter("@pGU3_NMEMIT", Me.pGU3_NMEMIT, CType(Nothing, String))
            persistence.AddParameter("@pGU3_CDERP", Me.pGU3_CDERP, CType(Nothing, String))
            persistence.AddParameter("@pGU3_CDCERP", Me.pGU3_CDCERP, CType(Nothing, String))
            persistence.AddParameter("@pGW1_NRROM", Me.pGW1_NRROM, CType(Nothing, String))
            persistence.AddParameter("@pGW1_TPFRET", Me.pGW1_TPFRET, CType(Nothing, String))
            persistence.AddParameter("@pGW1_DTSAI", Me.pGW1_DTSAI, CodeFluentPersistence.DefaultDateTimeValue)
            persistence.AddParameter("@pGW1_DTSAI_DIA", Me.pGW1_DTSAI_DIA, CType(Nothing, String))
            persistence.AddParameter("@pGW1_DTSAI_MES", Me.pGW1_DTSAI_MES, CType(Nothing, String))
            persistence.AddParameter("@pGW1_DTSAI_ANO", Me.pGW1_DTSAI_ANO, CType(Nothing, String))
            persistence.AddParameter("@pGW1_DSESP", Me.pGW1_DSESP, CType(Nothing, String))
            persistence.AddParameter("@pGW3_NRDF", Me.pGW3_NRDF, CType(Nothing, String))
            persistence.AddParameter("@pGW1_QTVOL", Me.pGW1_QTVOL, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@pGW8_VALOR_TOTAL_NOTA", Me.pGW8_VALOR_TOTAL_NOTA, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@pGW8_VALOR_BRUTO_TOTAL_NOTA", Me.pGW8_VALOR_BRUTO_TOTAL_NOTA, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@pVALOR_TOTAL_NF_FRETE_AGRUPADO", Me.pVALOR_TOTAL_NF_FRETE_AGRUPADO, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@pVALOR_FRETE_TOTAL", Me.pVALOR_FRETE_TOTAL, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@pPERC_NF_FRETE_AGRUPADO", Me.pPERC_NF_FRETE_AGRUPADO, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@pGWM_VLFRET_CFRT_CCAR_NOVOFRETE", Me.pGWM_VLFRET_CFRT_CCAR_NOVOFRETE, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@pGWM_VLFRET_RTDCCAR_TOTALNRDC", Me.pGWM_VLFRET_RTDCCAR_TOTALNRDC, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@pSTATUS_GFE", Me.pSTATUS_GFE, CType(Nothing, String))
            persistence.AddParameter("@pF2_PBRUTO_TOTALNRDC", Me.pF2_PBRUTO_TOTALNRDC, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@pF2_PLIQUI_TOTALNRDC", Me.pF2_PLIQUI_TOTALNRDC, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@_trackLastWriteUser", persistence.Context.User.Name)
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    Me.ReadRecordOnSave(reader)
                End If
                CodeFluentPersistence.NextResults(reader)
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Saved, false, false))
            Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
            Return true
        End Function
        
        Public Overloads Overridable Function Save() As Boolean Implements CodeFluent.Runtime.ICodeFluentEntity.Save
            Dim localSave As Boolean = Me.BaseSave(false)
            Return localSave
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)>  _
        Public Overloads Shared Function Save(ByVal aviacaoConhecimentoFreteAgrup As S5T.AviacaoConhecimentoFreteAgrup) As Boolean
            If (aviacaoConhecimentoFreteAgrup Is Nothing) Then
                Return false
            End If
            Dim ret As Boolean = aviacaoConhecimentoFreteAgrup.Save
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)>  _
        Public Shared Function Insert(ByVal aviacaoConhecimentoFreteAgrup As S5T.AviacaoConhecimentoFreteAgrup) As Boolean
            Dim ret As Boolean = S5T.AviacaoConhecimentoFreteAgrup.Save(aviacaoConhecimentoFreteAgrup)
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)>  _
        Public Overloads Shared Function Delete(ByVal aviacaoConhecimentoFreteAgrup As S5T.AviacaoConhecimentoFreteAgrup) As Boolean
            If (aviacaoConhecimentoFreteAgrup Is Nothing) Then
                Return false
            End If
            Dim ret As Boolean = aviacaoConhecimentoFreteAgrup.Delete
            Return ret
        End Function
        
        Public Function Trace() As String
            Dim stringBuilder As System.Text.StringBuilder = New System.Text.StringBuilder()
            Dim stringWriter As System.IO.StringWriter = New System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture)
            Dim writer As System.CodeDom.Compiler.IndentedTextWriter = New System.CodeDom.Compiler.IndentedTextWriter(stringWriter)
            Me.BaseTrace(writer)
            writer.Flush
            CType(writer,System.IDisposable).Dispose
            CType(stringWriter,System.IDisposable).Dispose
            Dim sr As String = stringBuilder.ToString
            Return sr
        End Function
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Sub CodeFluent_Runtime_ICodeFluentObject_Trace(ByVal writer As System.CodeDom.Compiler.IndentedTextWriter) Implements CodeFluent.Runtime.ICodeFluentObject.Trace
            Me.BaseTrace(writer)
        End Sub
        
        Protected Overridable Sub BaseTrace(ByVal writer As System.CodeDom.Compiler.IndentedTextWriter)
            writer.Write("[")
            writer.Write("pId=")
            writer.Write(Me.pId)
            writer.Write(",")
            writer.Write("pGW1_FILIAL=")
            writer.Write(Me.pGW1_FILIAL)
            writer.Write(",")
            writer.Write("pGW1_EMISDC=")
            writer.Write(Me.pGW1_EMISDC)
            writer.Write(",")
            writer.Write("pGW1_CDTPDC=")
            writer.Write(Me.pGW1_CDTPDC)
            writer.Write(",")
            writer.Write("pGV5_DSTPDC=")
            writer.Write(Me.pGV5_DSTPDC)
            writer.Write(",")
            writer.Write("pGW1_DTEMIS=")
            writer.Write(Me.pGW1_DTEMIS)
            writer.Write(",")
            writer.Write("pGW1_DTEMIS_DIA=")
            writer.Write(Me.pGW1_DTEMIS_DIA)
            writer.Write(",")
            writer.Write("pGW1_DTEMIS_MES=")
            writer.Write(Me.pGW1_DTEMIS_MES)
            writer.Write(",")
            writer.Write("pGW1_DTEMIS_ANO=")
            writer.Write(Me.pGW1_DTEMIS_ANO)
            writer.Write(",")
            writer.Write("pGW1_SERDC=")
            writer.Write(Me.pGW1_SERDC)
            writer.Write(",")
            writer.Write("pGW1_NRDC=")
            writer.Write(Me.pGW1_NRDC)
            writer.Write(",")
            writer.Write("pGW1_CDREM=")
            writer.Write(Me.pGW1_CDREM)
            writer.Write(",")
            writer.Write("pGU3_NMEMIT_REM=")
            writer.Write(Me.pGU3_NMEMIT_REM)
            writer.Write(",")
            writer.Write("pGU3_CDERP_REM=")
            writer.Write(Me.pGU3_CDERP_REM)
            writer.Write(",")
            writer.Write("pGU3_CDCERP_REM=")
            writer.Write(Me.pGU3_CDCERP_REM)
            writer.Write(",")
            writer.Write("pGW1_CDDEST=")
            writer.Write(Me.pGW1_CDDEST)
            writer.Write(",")
            writer.Write("pGU3_NMEMIT=")
            writer.Write(Me.pGU3_NMEMIT)
            writer.Write(",")
            writer.Write("pGU3_CDERP=")
            writer.Write(Me.pGU3_CDERP)
            writer.Write(",")
            writer.Write("pGU3_CDCERP=")
            writer.Write(Me.pGU3_CDCERP)
            writer.Write(",")
            writer.Write("pGW1_NRROM=")
            writer.Write(Me.pGW1_NRROM)
            writer.Write(",")
            writer.Write("pGW1_TPFRET=")
            writer.Write(Me.pGW1_TPFRET)
            writer.Write(",")
            writer.Write("pGW1_DTSAI=")
            writer.Write(Me.pGW1_DTSAI)
            writer.Write(",")
            writer.Write("pGW1_DTSAI_DIA=")
            writer.Write(Me.pGW1_DTSAI_DIA)
            writer.Write(",")
            writer.Write("pGW1_DTSAI_MES=")
            writer.Write(Me.pGW1_DTSAI_MES)
            writer.Write(",")
            writer.Write("pGW1_DTSAI_ANO=")
            writer.Write(Me.pGW1_DTSAI_ANO)
            writer.Write(",")
            writer.Write("pGW1_DSESP=")
            writer.Write(Me.pGW1_DSESP)
            writer.Write(",")
            writer.Write("pGW3_NRDF=")
            writer.Write(Me.pGW3_NRDF)
            writer.Write(",")
            writer.Write("pGW1_QTVOL=")
            writer.Write(Me.pGW1_QTVOL)
            writer.Write(",")
            writer.Write("pGW8_VALOR_TOTAL_NOTA=")
            writer.Write(Me.pGW8_VALOR_TOTAL_NOTA)
            writer.Write(",")
            writer.Write("pGW8_VALOR_BRUTO_TOTAL_NOTA=")
            writer.Write(Me.pGW8_VALOR_BRUTO_TOTAL_NOTA)
            writer.Write(",")
            writer.Write("pVALOR_TOTAL_NF_FRETE_AGRUPADO=")
            writer.Write(Me.pVALOR_TOTAL_NF_FRETE_AGRUPADO)
            writer.Write(",")
            writer.Write("pVALOR_FRETE_TOTAL=")
            writer.Write(Me.pVALOR_FRETE_TOTAL)
            writer.Write(",")
            writer.Write("pPERC_NF_FRETE_AGRUPADO=")
            writer.Write(Me.pPERC_NF_FRETE_AGRUPADO)
            writer.Write(",")
            writer.Write("pGWM_VLFRET_CFRT_CCAR_NOVOFRETE=")
            writer.Write(Me.pGWM_VLFRET_CFRT_CCAR_NOVOFRETE)
            writer.Write(",")
            writer.Write("pGWM_VLFRET_RTDCCAR_TOTALNRDC=")
            writer.Write(Me.pGWM_VLFRET_RTDCCAR_TOTALNRDC)
            writer.Write(",")
            writer.Write("pSTATUS_GFE=")
            writer.Write(Me.pSTATUS_GFE)
            writer.Write(",")
            writer.Write("pF2_PBRUTO_TOTALNRDC=")
            writer.Write(Me.pF2_PBRUTO_TOTALNRDC)
            writer.Write(",")
            writer.Write("pF2_PLIQUI_TOTALNRDC=")
            writer.Write(Me.pF2_PLIQUI_TOTALNRDC)
            writer.Write(", EntityState=")
            writer.Write(Me.EntityState)
            writer.Write("]")
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Shared Function LoadByEntityKey(ByVal key As String) As S5T.AviacaoConhecimentoFreteAgrup
            If (key Is String.Empty) Then
                Return Nothing
            End If
            Dim aviacaoConhecimentoFreteAgrup As S5T.AviacaoConhecimentoFreteAgrup
            Dim var As Long = CType(ConvertUtilities.ChangeType(key, GetType(Long), -1),Long)
            aviacaoConhecimentoFreteAgrup = S5T.AviacaoConhecimentoFreteAgrup.Load(var)
            Return aviacaoConhecimentoFreteAgrup
        End Function
        
        Protected Overridable Sub ValidateMember(ByVal culture As System.Globalization.CultureInfo, ByVal memberName As String, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException))
        End Sub
        
        Public Overloads Function Clone(ByVal deep As Boolean) As S5T.AviacaoConhecimentoFreteAgrup
            Dim aviacaoConhecimentoFreteAgrup As S5T.AviacaoConhecimentoFreteAgrup = New S5T.AviacaoConhecimentoFreteAgrup()
            Me.CopyTo(aviacaoConhecimentoFreteAgrup, deep)
            Return aviacaoConhecimentoFreteAgrup
        End Function
        
        Public Overloads Function Clone() As S5T.AviacaoConhecimentoFreteAgrup
            Dim localClone As S5T.AviacaoConhecimentoFreteAgrup = Me.Clone(true)
            Return localClone
        End Function
        
        Function System_ICloneable_Clone() As Object Implements System.ICloneable.Clone
            Dim localClone As Object = Me.Clone
            Return localClone
        End Function
        
        Public Overridable Sub CopyFrom(ByVal dict As System.Collections.IDictionary, ByVal deep As Boolean)
            If (dict Is Nothing) Then
                Throw New System.ArgumentNullException("dict")
            End If
            If (dict.Contains("pId") = true) Then
                Me.pId = CType(ConvertUtilities.ChangeType(dict("pId"), GetType(Long), -1),Long)
            End If
            If (dict.Contains("pGW3_NRDF") = true) Then
                Me.pGW3_NRDF = CType(ConvertUtilities.ChangeType(dict("pGW3_NRDF"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGW1_DSESP") = true) Then
                Me.pGW1_DSESP = CType(ConvertUtilities.ChangeType(dict("pGW1_DSESP"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGW8_VALOR_TOTAL_NOTA") = true) Then
                Me.pGW8_VALOR_TOTAL_NOTA = CType(ConvertUtilities.ChangeType(dict("pGW8_VALOR_TOTAL_NOTA"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("pGW1_QTVOL") = true) Then
                Me.pGW1_QTVOL = CType(ConvertUtilities.ChangeType(dict("pGW1_QTVOL"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("pGW1_DTSAI_ANO") = true) Then
                Me.pGW1_DTSAI_ANO = CType(ConvertUtilities.ChangeType(dict("pGW1_DTSAI_ANO"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGW1_DTSAI") = true) Then
                Me.pGW1_DTSAI = CType(ConvertUtilities.ChangeType(dict("pGW1_DTSAI"), GetType(Date), CodeFluentPersistence.DefaultDateTimeValue),Date)
            End If
            If (dict.Contains("pGW1_TPFRET") = true) Then
                Me.pGW1_TPFRET = CType(ConvertUtilities.ChangeType(dict("pGW1_TPFRET"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGW1_DTSAI_MES") = true) Then
                Me.pGW1_DTSAI_MES = CType(ConvertUtilities.ChangeType(dict("pGW1_DTSAI_MES"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGW1_DTSAI_DIA") = true) Then
                Me.pGW1_DTSAI_DIA = CType(ConvertUtilities.ChangeType(dict("pGW1_DTSAI_DIA"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pSTATUS_GFE") = true) Then
                Me.pSTATUS_GFE = CType(ConvertUtilities.ChangeType(dict("pSTATUS_GFE"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGWM_VLFRET_RTDCCAR_TOTALNRDC") = true) Then
                Me.pGWM_VLFRET_RTDCCAR_TOTALNRDC = CType(ConvertUtilities.ChangeType(dict("pGWM_VLFRET_RTDCCAR_TOTALNRDC"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("pF2_PLIQUI_TOTALNRDC") = true) Then
                Me.pF2_PLIQUI_TOTALNRDC = CType(ConvertUtilities.ChangeType(dict("pF2_PLIQUI_TOTALNRDC"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("pF2_PBRUTO_TOTALNRDC") = true) Then
                Me.pF2_PBRUTO_TOTALNRDC = CType(ConvertUtilities.ChangeType(dict("pF2_PBRUTO_TOTALNRDC"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("pGWM_VLFRET_CFRT_CCAR_NOVOFRETE") = true) Then
                Me.pGWM_VLFRET_CFRT_CCAR_NOVOFRETE = CType(ConvertUtilities.ChangeType(dict("pGWM_VLFRET_CFRT_CCAR_NOVOFRETE"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("pVALOR_TOTAL_NF_FRETE_AGRUPADO") = true) Then
                Me.pVALOR_TOTAL_NF_FRETE_AGRUPADO = CType(ConvertUtilities.ChangeType(dict("pVALOR_TOTAL_NF_FRETE_AGRUPADO"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("pGW8_VALOR_BRUTO_TOTAL_NOTA") = true) Then
                Me.pGW8_VALOR_BRUTO_TOTAL_NOTA = CType(ConvertUtilities.ChangeType(dict("pGW8_VALOR_BRUTO_TOTAL_NOTA"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("pPERC_NF_FRETE_AGRUPADO") = true) Then
                Me.pPERC_NF_FRETE_AGRUPADO = CType(ConvertUtilities.ChangeType(dict("pPERC_NF_FRETE_AGRUPADO"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("pVALOR_FRETE_TOTAL") = true) Then
                Me.pVALOR_FRETE_TOTAL = CType(ConvertUtilities.ChangeType(dict("pVALOR_FRETE_TOTAL"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("pGW1_NRROM") = true) Then
                Me.pGW1_NRROM = CType(ConvertUtilities.ChangeType(dict("pGW1_NRROM"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGW1_DTEMIS_MES") = true) Then
                Me.pGW1_DTEMIS_MES = CType(ConvertUtilities.ChangeType(dict("pGW1_DTEMIS_MES"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGW1_DTEMIS_DIA") = true) Then
                Me.pGW1_DTEMIS_DIA = CType(ConvertUtilities.ChangeType(dict("pGW1_DTEMIS_DIA"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGW1_SERDC") = true) Then
                Me.pGW1_SERDC = CType(ConvertUtilities.ChangeType(dict("pGW1_SERDC"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGW1_DTEMIS_ANO") = true) Then
                Me.pGW1_DTEMIS_ANO = CType(ConvertUtilities.ChangeType(dict("pGW1_DTEMIS_ANO"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGW1_DTEMIS") = true) Then
                Me.pGW1_DTEMIS = CType(ConvertUtilities.ChangeType(dict("pGW1_DTEMIS"), GetType(Date), CodeFluentPersistence.DefaultDateTimeValue),Date)
            End If
            If (dict.Contains("pGW1_EMISDC") = true) Then
                Me.pGW1_EMISDC = CType(ConvertUtilities.ChangeType(dict("pGW1_EMISDC"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGW1_FILIAL") = true) Then
                Me.pGW1_FILIAL = CType(ConvertUtilities.ChangeType(dict("pGW1_FILIAL"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGV5_DSTPDC") = true) Then
                Me.pGV5_DSTPDC = CType(ConvertUtilities.ChangeType(dict("pGV5_DSTPDC"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGW1_CDTPDC") = true) Then
                Me.pGW1_CDTPDC = CType(ConvertUtilities.ChangeType(dict("pGW1_CDTPDC"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGU3_NMEMIT") = true) Then
                Me.pGU3_NMEMIT = CType(ConvertUtilities.ChangeType(dict("pGU3_NMEMIT"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGW1_CDDEST") = true) Then
                Me.pGW1_CDDEST = CType(ConvertUtilities.ChangeType(dict("pGW1_CDDEST"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGU3_CDCERP") = true) Then
                Me.pGU3_CDCERP = CType(ConvertUtilities.ChangeType(dict("pGU3_CDCERP"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGU3_CDERP") = true) Then
                Me.pGU3_CDERP = CType(ConvertUtilities.ChangeType(dict("pGU3_CDERP"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGU3_CDCERP_REM") = true) Then
                Me.pGU3_CDCERP_REM = CType(ConvertUtilities.ChangeType(dict("pGU3_CDCERP_REM"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGW1_CDREM") = true) Then
                Me.pGW1_CDREM = CType(ConvertUtilities.ChangeType(dict("pGW1_CDREM"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGW1_NRDC") = true) Then
                Me.pGW1_NRDC = CType(ConvertUtilities.ChangeType(dict("pGW1_NRDC"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGU3_CDERP_REM") = true) Then
                Me.pGU3_CDERP_REM = CType(ConvertUtilities.ChangeType(dict("pGU3_CDERP_REM"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pGU3_NMEMIT_REM") = true) Then
                Me.pGU3_NMEMIT_REM = CType(ConvertUtilities.ChangeType(dict("pGU3_NMEMIT_REM"), GetType(String), CType(Nothing, String)),String)
            End If
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyFrom, false, dict))
        End Sub
        
        Public Overloads Overridable Sub CopyTo(ByVal aviacaoConhecimentoFreteAgrup As S5T.AviacaoConhecimentoFreteAgrup, ByVal deep As Boolean)
            If (aviacaoConhecimentoFreteAgrup Is Nothing) Then
                Throw New System.ArgumentNullException("aviacaoConhecimentoFreteAgrup")
            End If
            aviacaoConhecimentoFreteAgrup.pId = Me.pId
            aviacaoConhecimentoFreteAgrup.pGW3_NRDF = Me.pGW3_NRDF
            aviacaoConhecimentoFreteAgrup.pGW1_DSESP = Me.pGW1_DSESP
            aviacaoConhecimentoFreteAgrup.pGW8_VALOR_TOTAL_NOTA = Me.pGW8_VALOR_TOTAL_NOTA
            aviacaoConhecimentoFreteAgrup.pGW1_QTVOL = Me.pGW1_QTVOL
            aviacaoConhecimentoFreteAgrup.pGW1_DTSAI_ANO = Me.pGW1_DTSAI_ANO
            aviacaoConhecimentoFreteAgrup.pGW1_DTSAI = Me.pGW1_DTSAI
            aviacaoConhecimentoFreteAgrup.pGW1_TPFRET = Me.pGW1_TPFRET
            aviacaoConhecimentoFreteAgrup.pGW1_DTSAI_MES = Me.pGW1_DTSAI_MES
            aviacaoConhecimentoFreteAgrup.pGW1_DTSAI_DIA = Me.pGW1_DTSAI_DIA
            aviacaoConhecimentoFreteAgrup.pSTATUS_GFE = Me.pSTATUS_GFE
            aviacaoConhecimentoFreteAgrup.pGWM_VLFRET_RTDCCAR_TOTALNRDC = Me.pGWM_VLFRET_RTDCCAR_TOTALNRDC
            aviacaoConhecimentoFreteAgrup.pF2_PLIQUI_TOTALNRDC = Me.pF2_PLIQUI_TOTALNRDC
            aviacaoConhecimentoFreteAgrup.pF2_PBRUTO_TOTALNRDC = Me.pF2_PBRUTO_TOTALNRDC
            aviacaoConhecimentoFreteAgrup.pGWM_VLFRET_CFRT_CCAR_NOVOFRETE = Me.pGWM_VLFRET_CFRT_CCAR_NOVOFRETE
            aviacaoConhecimentoFreteAgrup.pVALOR_TOTAL_NF_FRETE_AGRUPADO = Me.pVALOR_TOTAL_NF_FRETE_AGRUPADO
            aviacaoConhecimentoFreteAgrup.pGW8_VALOR_BRUTO_TOTAL_NOTA = Me.pGW8_VALOR_BRUTO_TOTAL_NOTA
            aviacaoConhecimentoFreteAgrup.pPERC_NF_FRETE_AGRUPADO = Me.pPERC_NF_FRETE_AGRUPADO
            aviacaoConhecimentoFreteAgrup.pVALOR_FRETE_TOTAL = Me.pVALOR_FRETE_TOTAL
            aviacaoConhecimentoFreteAgrup.pGW1_NRROM = Me.pGW1_NRROM
            aviacaoConhecimentoFreteAgrup.pGW1_DTEMIS_MES = Me.pGW1_DTEMIS_MES
            aviacaoConhecimentoFreteAgrup.pGW1_DTEMIS_DIA = Me.pGW1_DTEMIS_DIA
            aviacaoConhecimentoFreteAgrup.pGW1_SERDC = Me.pGW1_SERDC
            aviacaoConhecimentoFreteAgrup.pGW1_DTEMIS_ANO = Me.pGW1_DTEMIS_ANO
            aviacaoConhecimentoFreteAgrup.pGW1_DTEMIS = Me.pGW1_DTEMIS
            aviacaoConhecimentoFreteAgrup.pGW1_EMISDC = Me.pGW1_EMISDC
            aviacaoConhecimentoFreteAgrup.pGW1_FILIAL = Me.pGW1_FILIAL
            aviacaoConhecimentoFreteAgrup.pGV5_DSTPDC = Me.pGV5_DSTPDC
            aviacaoConhecimentoFreteAgrup.pGW1_CDTPDC = Me.pGW1_CDTPDC
            aviacaoConhecimentoFreteAgrup.pGU3_NMEMIT = Me.pGU3_NMEMIT
            aviacaoConhecimentoFreteAgrup.pGW1_CDDEST = Me.pGW1_CDDEST
            aviacaoConhecimentoFreteAgrup.pGU3_CDCERP = Me.pGU3_CDCERP
            aviacaoConhecimentoFreteAgrup.pGU3_CDERP = Me.pGU3_CDERP
            aviacaoConhecimentoFreteAgrup.pGU3_CDCERP_REM = Me.pGU3_CDCERP_REM
            aviacaoConhecimentoFreteAgrup.pGW1_CDREM = Me.pGW1_CDREM
            aviacaoConhecimentoFreteAgrup.pGW1_NRDC = Me.pGW1_NRDC
            aviacaoConhecimentoFreteAgrup.pGU3_CDERP_REM = Me.pGU3_CDERP_REM
            aviacaoConhecimentoFreteAgrup.pGU3_NMEMIT_REM = Me.pGU3_NMEMIT_REM
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, aviacaoConhecimentoFreteAgrup))
        End Sub
        
        Public Overloads Overridable Sub CopyTo(ByVal dict As System.Collections.IDictionary, ByVal deep As Boolean)
            If (dict Is Nothing) Then
                Throw New System.ArgumentNullException("dict")
            End If
            dict("pId") = Me.pId
            dict("pGW3_NRDF") = Me.pGW3_NRDF
            dict("pGW1_DSESP") = Me.pGW1_DSESP
            dict("pGW8_VALOR_TOTAL_NOTA") = Me.pGW8_VALOR_TOTAL_NOTA
            dict("pGW1_QTVOL") = Me.pGW1_QTVOL
            dict("pGW1_DTSAI_ANO") = Me.pGW1_DTSAI_ANO
            dict("pGW1_DTSAI") = Me.pGW1_DTSAI
            dict("pGW1_TPFRET") = Me.pGW1_TPFRET
            dict("pGW1_DTSAI_MES") = Me.pGW1_DTSAI_MES
            dict("pGW1_DTSAI_DIA") = Me.pGW1_DTSAI_DIA
            dict("pSTATUS_GFE") = Me.pSTATUS_GFE
            dict("pGWM_VLFRET_RTDCCAR_TOTALNRDC") = Me.pGWM_VLFRET_RTDCCAR_TOTALNRDC
            dict("pF2_PLIQUI_TOTALNRDC") = Me.pF2_PLIQUI_TOTALNRDC
            dict("pF2_PBRUTO_TOTALNRDC") = Me.pF2_PBRUTO_TOTALNRDC
            dict("pGWM_VLFRET_CFRT_CCAR_NOVOFRETE") = Me.pGWM_VLFRET_CFRT_CCAR_NOVOFRETE
            dict("pVALOR_TOTAL_NF_FRETE_AGRUPADO") = Me.pVALOR_TOTAL_NF_FRETE_AGRUPADO
            dict("pGW8_VALOR_BRUTO_TOTAL_NOTA") = Me.pGW8_VALOR_BRUTO_TOTAL_NOTA
            dict("pPERC_NF_FRETE_AGRUPADO") = Me.pPERC_NF_FRETE_AGRUPADO
            dict("pVALOR_FRETE_TOTAL") = Me.pVALOR_FRETE_TOTAL
            dict("pGW1_NRROM") = Me.pGW1_NRROM
            dict("pGW1_DTEMIS_MES") = Me.pGW1_DTEMIS_MES
            dict("pGW1_DTEMIS_DIA") = Me.pGW1_DTEMIS_DIA
            dict("pGW1_SERDC") = Me.pGW1_SERDC
            dict("pGW1_DTEMIS_ANO") = Me.pGW1_DTEMIS_ANO
            dict("pGW1_DTEMIS") = Me.pGW1_DTEMIS
            dict("pGW1_EMISDC") = Me.pGW1_EMISDC
            dict("pGW1_FILIAL") = Me.pGW1_FILIAL
            dict("pGV5_DSTPDC") = Me.pGV5_DSTPDC
            dict("pGW1_CDTPDC") = Me.pGW1_CDTPDC
            dict("pGU3_NMEMIT") = Me.pGU3_NMEMIT
            dict("pGW1_CDDEST") = Me.pGW1_CDDEST
            dict("pGU3_CDCERP") = Me.pGU3_CDCERP
            dict("pGU3_CDERP") = Me.pGU3_CDERP
            dict("pGU3_CDCERP_REM") = Me.pGU3_CDCERP_REM
            dict("pGW1_CDREM") = Me.pGW1_CDREM
            dict("pGW1_NRDC") = Me.pGW1_NRDC
            dict("pGU3_CDERP_REM") = Me.pGU3_CDERP_REM
            dict("pGU3_NMEMIT_REM") = Me.pGU3_NMEMIT_REM
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, dict))
        End Sub
        
        Protected Sub OnCollectionKeyChanged(ByVal key As Long)
            If (Not (Me.KeyChangedEvent) Is Nothing) Then
                RaiseEvent KeyChanged(Me, New CodeFluent.Runtime.Utilities.KeyChangedEventArgs(Of Long)(key))
            End If
        End Sub
    End Class
End Namespace
