'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CodeFluent.Runtime
Imports CodeFluent.Runtime.Utilities

Namespace S5T
    
    'CodeFluent Entities generated (http://www.softfluent.com). Date: .
    <System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.01234.05678"),  _
     System.SerializableAttribute(),  _
     System.ComponentModel.DataObjectAttribute(),  _
     System.Diagnostics.DebuggerDisplayAttribute("EK={EntityKey}, G1_COMP={G1_COMP}, pId={pId}"),  _
     System.ComponentModel.TypeConverterAttribute(GetType(CodeFluent.Runtime.Design.NameTypeConverter))>  _
    Partial Public Class FracionamentoMov
        Implements System.ICloneable, System.IComparable, System.IComparable(Of S5T.FracionamentoMov), CodeFluent.Runtime.ICodeFluentCollectionEntity(Of Long), System.ComponentModel.IDataErrorInfo, CodeFluent.Runtime.ICodeFluentMemberValidator, CodeFluent.Runtime.ICodeFluentSummaryValidator, System.IEquatable(Of S5T.FracionamentoMov)
        
        Private _raisePropertyChangedEvents As Boolean = true
        
        Private _entityState As CodeFluent.Runtime.CodeFluentEntityState
        
        Private _pId As Long = -1
        
        Private _g1_COMP As String = CType(Nothing, String)
        
        Private _b1_DESC As String = CType(Nothing, String)
        
        Private _g1_QUANT As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _g1_ZZQMIN As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _g1_ZZQMAX As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _pPesoPesado As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _pLote As String = CType(Nothing, String)
        
        Private _oFracionamentopId As Long = -1
        
        <System.NonSerializedAttribute()>  _
        Private _oFracionamento As S5T.Fracionamento = Nothing
        
        Private _pDataMov As Date = CodeFluentPersistence.DefaultDateTimeValue
        
        Private _pUsuario As String = CType(Nothing, String)
        
        Private _b1_UM As String = CType(Nothing, String)
        
        Private _pTara As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Private _pVez As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Public Sub New()
            MyBase.New
            Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created
        End Sub
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Overridable Property RaisePropertyChangedEvents() As Boolean
            Get
                Return Me._raisePropertyChangedEvents
            End Get
            Set
                Me._raisePropertyChangedEvents = value
            End Set
        End Property
        
        Public Overridable Property EntityKey() As String Implements CodeFluent.Runtime.ICodeFluentEntity.EntityKey
            Get
                Return Me.pId.ToString
            End Get
            Set
                Me.pId = CType(ConvertUtilities.ChangeType(value, GetType(Long), -1),Long)
            End Set
        End Property
        
        Public Overridable ReadOnly Property EntityDisplayName() As String Implements CodeFluent.Runtime.ICodeFluentEntity.EntityDisplayName
            Get
                Return Me.G1_COMP
            End Get
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(-1,Long)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Long)),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property pId() As Long
            Get
                Return Me._pId
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of Long).Default.Equals(value, Me._pId) = true) Then
                    Return
                End If
                Dim oldKey As Long = Me._pId
                Me._pId = value
                Try 
                    Me.OnCollectionKeyChanged(oldKey)
                Catch __exception As System.ArgumentException
                    Me._pId = oldKey
                    Return
                End Try
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pId"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property G1_COMP() As String
            Get
                Return Me._g1_COMP
            End Get
            Set
                Me._g1_COMP = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("G1_COMP"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property B1_DESC() As String
            Get
                Return Me._b1_DESC
            End Get
            Set
                Me._b1_DESC = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("B1_DESC"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property G1_QUANT() As Double
            Get
                Return Me._g1_QUANT
            End Get
            Set
                Me._g1_QUANT = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("G1_QUANT"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property G1_ZZQMIN() As Double
            Get
                Return Me._g1_ZZQMIN
            End Get
            Set
                Me._g1_ZZQMIN = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("G1_ZZQMIN"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property G1_ZZQMAX() As Double
            Get
                Return Me._g1_ZZQMAX
            End Get
            Set
                Me._g1_ZZQMAX = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("G1_ZZQMAX"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property pPesoPesado() As Double
            Get
                Return Me._pPesoPesado
            End Get
            Set
                Me._pPesoPesado = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pPesoPesado"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pLote() As String
            Get
                Return Me._pLote
            End Get
            Set
                Me._pLote = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pLote"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property oFracionamentopId() As Long
            Get
                If ((Me._oFracionamentopId = -1)  _
                            AndAlso (Not (Me._oFracionamento) Is Nothing)) Then
                    Me._oFracionamentopId = Me._oFracionamento.pId
                End If
                Return Me._oFracionamentopId
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of Long).Default.Equals(value, Me.oFracionamentopId) = true) Then
                    Return
                End If
                Me._oFracionamento = Nothing
                Me._oFracionamentopId = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("oFracionamento"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("oFracionamentopId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property oFracionamento() As S5T.Fracionamento
            Get
                If (Me._oFracionamento Is Nothing) Then
                    Me._oFracionamento = S5T.Fracionamento.Load(Me._oFracionamentopId)
                End If
                Return Me._oFracionamento
            End Get
            Set
                Me._oFracionamentopId = -1
                Me._oFracionamento = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("oFracionamento"))
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("oFracionamentopId"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Date))>  _
        Public Property pDataMov() As Date
            Get
                Return Me._pDataMov
            End Get
            Set
                Me._pDataMov = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pDataMov"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pUsuario() As String
            Get
                Return Me._pUsuario
            End Get
            Set
                Me._pUsuario = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pUsuario"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property B1_UM() As String
            Get
                Return Me._b1_UM
            End Get
            Set
                Me._b1_UM = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("B1_UM"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property pTara() As Double
            Get
                Return Me._pTara
            End Get
            Set
                Me._pTara = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pTara"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property pVez() As Integer
            Get
                Return Me._pVez
            End Get
            Set
                Me._pVez = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pVez"))
            End Set
        End Property
        
        ReadOnly Property System_ComponentModel_IDataErrorInfo_Error() As String Implements System.ComponentModel.IDataErrorInfo.[Error]
            Get
                Return Me.Validate(System.Globalization.CultureInfo.CurrentCulture)
            End Get
        End Property
        
        ReadOnly Property System_ComponentModel_IDataErrorInfo_Item(ByVal columnName As String) As String Implements System.ComponentModel.IDataErrorInfo.Item
            Get
                Return CodeFluentPersistence.ValidateMember(System.Globalization.CultureInfo.CurrentCulture, Me, columnName, Nothing)
            End Get
        End Property
        
        ReadOnly Property CodeFluent_Runtime_Utilities_IKeyable_System_Int64__Key() As Long Implements CodeFluent.Runtime.Utilities.IKeyable(Of Long).Key
            Get
                Return Me.pId
            End Get
        End Property
        
        Public Overridable Property EntityState() As CodeFluent.Runtime.CodeFluentEntityState Implements CodeFluent.Runtime.ICodeFluentEntity.EntityState
            Get
                Return Me._entityState
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of CodeFluent.Runtime.CodeFluentEntityState).Default.Equals(value, Me.EntityState) = true) Then
                    Return
                End If
                If ((Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted)  _
                            AndAlso (value = CodeFluent.Runtime.CodeFluentEntityState.Modified)) Then
                    Return
                End If
                If ((Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created)  _
                            AndAlso (value = CodeFluent.Runtime.CodeFluentEntityState.Modified)) Then
                    Return
                End If
                Me._entityState = value
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("EntityState"))
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Public Event EntityAction As CodeFluent.Runtime.CodeFluentEntityActionEventHandler Implements CodeFluent.Runtime.ICodeFluentEntity.EntityAction
        
        Public Event KeyChanged As System.EventHandler(Of CodeFluent.Runtime.Utilities.KeyChangedEventArgs(Of Long)) Implements CodeFluent.Runtime.Utilities.IKeyable(Of Long).KeyChanged
        
        Protected Overridable Sub OnPropertyChanged(ByVal e As System.ComponentModel.PropertyChangedEventArgs)
            If (Me.RaisePropertyChangedEvents = false) Then
                Return
            End If
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, e)
            End If
        End Sub
        
        Protected Overridable Sub OnEntityAction(ByVal e As CodeFluent.Runtime.CodeFluentEntityActionEventArgs)
            If (Not (Me.EntityActionEvent) Is Nothing) Then
                RaiseEvent EntityAction(Me, e)
            End If
        End Sub
        
        Public Overloads Overridable Function Equals(ByVal fracionamentoMov As S5T.FracionamentoMov) As Boolean Implements System.IEquatable(Of S5T.FracionamentoMov).Equals
            If (fracionamentoMov Is Nothing) Then
                Return false
            End If
            If (Me.pId = -1) Then
                Return MyBase.Equals(fracionamentoMov)
            End If
            Return (Me.pId.Equals(fracionamentoMov.pId) = true)
        End Function
        
        Public Overloads Overrides Function GetHashCode() As Integer
            Return Me.pId.GetHashCode
        End Function
        
        Public Overloads Overrides Function Equals(ByVal obj As Object) As Boolean
            Dim fracionamentoMov As S5T.FracionamentoMov = Nothing
            Try 
                fracionamentoMov = CType(obj,S5T.FracionamentoMov)
            Catch icex As System.InvalidCastException
                fracionamentoMov = Nothing
            End Try
            Return Me.Equals(fracionamentoMov)
        End Function
        
        Overridable Function System_IComparable_CompareTo(ByVal value As Object) As Integer Implements System.IComparable.CompareTo
            Dim fracionamentoMov As S5T.FracionamentoMov = Nothing
            Try 
                fracionamentoMov = CType(value,S5T.FracionamentoMov)
            Catch icex As System.InvalidCastException
                fracionamentoMov = Nothing
            End Try
            If (fracionamentoMov Is Nothing) Then
                Throw New System.ArgumentException("value")
            End If
            Dim localCompareTo As Integer = Me.CompareTo(fracionamentoMov)
            Return localCompareTo
        End Function
        
        Public Overridable Function CompareTo(ByVal fracionamentoMov As S5T.FracionamentoMov) As Integer Implements System.IComparable(Of S5T.FracionamentoMov).CompareTo
            If (fracionamentoMov Is Nothing) Then
                Throw New System.ArgumentNullException("fracionamentoMov")
            End If
            Dim localCompareTo As Integer = Me.pId.CompareTo(fracionamentoMov.pId)
            Return localCompareTo
        End Function
        
        Public Overloads Overridable Function Validate(ByVal culture As System.Globalization.CultureInfo) As String
            Return CodeFluentPersistence.Validate(culture, Me, Nothing)
        End Function
        
        Public Overloads Overridable Sub Validate(ByVal culture As System.Globalization.CultureInfo, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException)) Implements CodeFluent.Runtime.ICodeFluentSummaryValidator.Validate
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Validating, true, results)
            evt.Culture = culture
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Dim externalValidate As String
                If (Not (evt.Argument) Is Nothing) Then
                    externalValidate = evt.Argument.ToString
                Else
                    externalValidate = S5T.Resources.Manager.GetStringWithDefault(culture, "S5T.FracionamentoMov.ExternalValidate", "Type 'S5T.FracionamentoMov' cannot be validated.", Nothing)
                End If
                CodeFluentPersistence.AddValidationError(results, externalValidate)
            End If
            CodeFluentPersistence.ValidateMember(culture, results, Me, Nothing)
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Validated, false, results))
        End Sub
        
        Public Overloads Sub Validate()
            Dim var As String = Me.Validate(System.Globalization.CultureInfo.CurrentCulture)
            If (Not (var) Is Nothing) Then
                Throw New CodeFluent.Runtime.CodeFluentValidationException(var)
            End If
        End Sub
        
        Function CodeFluent_Runtime_ICodeFluentValidator_Validate(ByVal culture As System.Globalization.CultureInfo) As String Implements CodeFluent.Runtime.ICodeFluentValidator.Validate
            Dim localValidate As String = Me.Validate(culture)
            Return localValidate
        End Function
        
        Sub CodeFluent_Runtime_ICodeFluentMemberValidator_Validate(ByVal culture As System.Globalization.CultureInfo, ByVal memberName As String, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException)) Implements CodeFluent.Runtime.ICodeFluentMemberValidator.Validate
            Me.ValidateMember(culture, memberName, results)
        End Sub
        
        Public Overloads Overridable Function Delete() As Boolean Implements CodeFluent.Runtime.ICodeFluentEntity.Delete
            Dim ret As Boolean = false
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Deleting, true)
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Return ret
            End If
            If (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted) Then
                Return ret
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "FracionamentoMov", "Delete")
            persistence.AddParameter("@pId", Me.pId, CType(-1,Long))
            persistence.ExecuteNonQuery
            Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Deleted, false, false))
            ret = true
            Return ret
        End Function
        
        Protected Overridable Sub ReadRecord(ByVal reader As System.Data.IDataReader, ByVal options As CodeFluent.Runtime.CodeFluentReloadOptions)
            If (reader Is Nothing) Then
                Throw New System.ArgumentNullException("reader")
            End If
            If (((options And CodeFluent.Runtime.CodeFluentReloadOptions.Properties)  _
                        = 0)  _
                        = false) Then
                Me._pId = CodeFluentPersistence.GetReaderValue(reader, "pId", CType(-1,Long))
                Me._g1_COMP = CodeFluentPersistence.GetReaderValue(reader, "G1_COMP", CType(CType(Nothing, String),String))
                Me._b1_DESC = CodeFluentPersistence.GetReaderValue(reader, "B1_DESC", CType(CType(Nothing, String),String))
                Me._g1_QUANT = CodeFluentPersistence.GetReaderValue(reader, "G1_QUANT", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._g1_ZZQMIN = CodeFluentPersistence.GetReaderValue(reader, "G1_ZZQMIN", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._g1_ZZQMAX = CodeFluentPersistence.GetReaderValue(reader, "G1_ZZQMAX", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._pPesoPesado = CodeFluentPersistence.GetReaderValue(reader, "pPesoPesado", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._pLote = CodeFluentPersistence.GetReaderValue(reader, "pLote", CType(CType(Nothing, String),String))
                Me.oFracionamentopId = CodeFluentPersistence.GetReaderValue(reader, "oFracionamento_pId", CType(-1,Long))
                Me._pDataMov = CodeFluentPersistence.GetReaderValue(reader, "pDataMov", CType(CodeFluentPersistence.DefaultDateTimeValue,Date))
                Me._pUsuario = CodeFluentPersistence.GetReaderValue(reader, "pUsuario", CType(CType(Nothing, String),String))
                Me._b1_UM = CodeFluentPersistence.GetReaderValue(reader, "B1_UM", CType(CType(Nothing, String),String))
                Me._pTara = CodeFluentPersistence.GetReaderValue(reader, "pTara", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
                Me._pVez = CodeFluentPersistence.GetReaderValue(reader, "pVez", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
            End If
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecord, false, false))
        End Sub
        
        Sub CodeFluent_Runtime_ICodeFluentEntity_ReadRecord(ByVal reader As System.Data.IDataReader) Implements CodeFluent.Runtime.ICodeFluentEntity.ReadRecord
            Me.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
        End Sub
        
        Protected Overridable Sub ReadRecordOnSave(ByVal reader As System.Data.IDataReader)
            If (reader Is Nothing) Then
                Throw New System.ArgumentNullException("reader")
            End If
            Me._pId = CodeFluentPersistence.GetReaderValue(reader, "pId", CType(-1,Long))
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecordOnSave, false, false))
        End Sub
        
        Sub CodeFluent_Runtime_ICodeFluentEntity_ReadRecordOnSave(ByVal reader As System.Data.IDataReader) Implements CodeFluent.Runtime.ICodeFluentEntity.ReadRecordOnSave
            Me.ReadRecordOnSave(reader)
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Shared Function Load(ByVal pId As Long) As S5T.FracionamentoMov
            If (pId = -1) Then
                Return Nothing
            End If
            Dim fracionamentoMov As S5T.FracionamentoMov = New S5T.FracionamentoMov()
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "FracionamentoMov", "Load")
            persistence.AddParameter("@pId", pId, CType(-1,Long))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    fracionamentoMov.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
                    fracionamentoMov.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    Return fracionamentoMov
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return Nothing
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], false)>  _
        Public Shared Function LoadBypId(ByVal pId As Long) As S5T.FracionamentoMov
            If (pId = -1) Then
                Return Nothing
            End If
            Dim fracionamentoMov As S5T.FracionamentoMov = New S5T.FracionamentoMov()
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "FracionamentoMov", "LoadBypId")
            persistence.AddParameter("@pId", pId, CType(-1,Long))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    fracionamentoMov.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
                    fracionamentoMov.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    Return fracionamentoMov
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return Nothing
        End Function
        
        Public Shared Sub GravaOrdem(ByVal parFracionamentoMovView As System.Collections.Generic.List(Of S5T.FracionamentoMovViewGrid))
            Dim scope As System.Transactions.TransactionScope = Nothing
            Try 
                Dim options As System.Transactions.TransactionOptions = New System.Transactions.TransactionOptions()
                scope = New System.Transactions.TransactionScope(System.Transactions.TransactionScopeOption.Required, options)
GravaOrdemPartial(parFracionamentoMovView)
                scope.Complete
            Finally
                If (Not (scope) Is Nothing) Then
                    scope.Dispose
                End If
            End Try
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], false)>  _
        Public Shared Function LoadByProduto(ByVal parProdCodigo As String) As S5T.FracionamentoMov
            If (parProdCodigo Is CType(Nothing, String)) Then
                Return Nothing
            End If
            Dim fracionamentoMov As S5T.FracionamentoMov = New S5T.FracionamentoMov()
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "FracionamentoMov", "LoadByProduto")
            persistence.AddParameter("@parProdCodigo", parProdCodigo)
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    fracionamentoMov.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
                    fracionamentoMov.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    Return fracionamentoMov
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return Nothing
        End Function
        
        Public Overridable Function Reload(ByVal options As CodeFluent.Runtime.CodeFluentReloadOptions) As Boolean
            Dim ret As Boolean = false
            If (Me.pId = -1) Then
                Return ret
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "FracionamentoMov", "Load")
            persistence.AddParameter("@pId", Me.pId, CType(-1,Long))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    Me.ReadRecord(reader, options)
                    Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    ret = true
                Else
                    Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return ret
        End Function
        
        Protected Overridable Function BaseSave(ByVal force As Boolean) As Boolean
            If (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted) Then
                S5T.FracionamentoMov.Delete(Me)
                Return false
            End If
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Saving, true)
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Return false
            End If
            CodeFluentPersistence.ThrowIfDeleted(Me)
            Me.Validate
            If ((force = false)  _
                        AndAlso (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged)) Then
                Return false
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "FracionamentoMov", "Save")
            persistence.AddParameter("@pId", Me.pId, CType(-1,Long))
            persistence.AddParameter("@G1_COMP", Me.G1_COMP, CType(Nothing, String))
            persistence.AddParameter("@B1_DESC", Me.B1_DESC, CType(Nothing, String))
            persistence.AddParameter("@G1_QUANT", Me.G1_QUANT, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@G1_ZZQMIN", Me.G1_ZZQMIN, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@G1_ZZQMAX", Me.G1_ZZQMAX, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@pPesoPesado", Me.pPesoPesado, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@pLote", Me.pLote, CType(Nothing, String))
            persistence.AddParameter("@oFracionamento_pId", Me.oFracionamentopId, CType(-1,Long))
            persistence.AddParameter("@pDataMov", Me.pDataMov, CodeFluentPersistence.DefaultDateTimeValue)
            persistence.AddParameter("@pUsuario", Me.pUsuario, CType(Nothing, String))
            persistence.AddParameter("@B1_UM", Me.B1_UM, CType(Nothing, String))
            persistence.AddParameter("@pTara", Me.pTara, CodeFluentPersistence.DefaultDoubleValue)
            persistence.AddParameter("@pVez", Me.pVez, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@_trackLastWriteUser", persistence.Context.User.Name)
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    Me.ReadRecordOnSave(reader)
                End If
                CodeFluentPersistence.NextResults(reader)
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Saved, false, false))
            Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
            Return true
        End Function
        
        Public Overloads Overridable Function Save() As Boolean Implements CodeFluent.Runtime.ICodeFluentEntity.Save
            Me.OnBeforeSave
            Dim localSave As Boolean = Me.BaseSave(false)
            Return localSave
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)>  _
        Public Overloads Shared Function Save(ByVal fracionamentoMov As S5T.FracionamentoMov) As Boolean
            If (fracionamentoMov Is Nothing) Then
                Return false
            End If
            Dim ret As Boolean = fracionamentoMov.Save
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)>  _
        Public Shared Function Insert(ByVal fracionamentoMov As S5T.FracionamentoMov) As Boolean
            Dim ret As Boolean = S5T.FracionamentoMov.Save(fracionamentoMov)
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)>  _
        Public Overloads Shared Function Delete(ByVal fracionamentoMov As S5T.FracionamentoMov) As Boolean
            If (fracionamentoMov Is Nothing) Then
                Return false
            End If
            Dim ret As Boolean = fracionamentoMov.Delete
            Return ret
        End Function
        
        Public Function Trace() As String
            Dim stringBuilder As System.Text.StringBuilder = New System.Text.StringBuilder()
            Dim stringWriter As System.IO.StringWriter = New System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture)
            Dim writer As System.CodeDom.Compiler.IndentedTextWriter = New System.CodeDom.Compiler.IndentedTextWriter(stringWriter)
            Me.BaseTrace(writer)
            writer.Flush
            CType(writer,System.IDisposable).Dispose
            CType(stringWriter,System.IDisposable).Dispose
            Dim sr As String = stringBuilder.ToString
            Return sr
        End Function
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Sub CodeFluent_Runtime_ICodeFluentObject_Trace(ByVal writer As System.CodeDom.Compiler.IndentedTextWriter) Implements CodeFluent.Runtime.ICodeFluentObject.Trace
            Me.BaseTrace(writer)
        End Sub
        
        Protected Overridable Sub BaseTrace(ByVal writer As System.CodeDom.Compiler.IndentedTextWriter)
            writer.Write("[")
            writer.Write("pId=")
            writer.Write(Me.pId)
            writer.Write(",")
            writer.Write("G1_COMP=")
            writer.Write(Me.G1_COMP)
            writer.Write(",")
            writer.Write("B1_DESC=")
            writer.Write(Me.B1_DESC)
            writer.Write(",")
            writer.Write("G1_QUANT=")
            writer.Write(Me.G1_QUANT)
            writer.Write(",")
            writer.Write("G1_ZZQMIN=")
            writer.Write(Me.G1_ZZQMIN)
            writer.Write(",")
            writer.Write("G1_ZZQMAX=")
            writer.Write(Me.G1_ZZQMAX)
            writer.Write(",")
            writer.Write("pPesoPesado=")
            writer.Write(Me.pPesoPesado)
            writer.Write(",")
            writer.Write("pLote=")
            writer.Write(Me.pLote)
            writer.Write(",")
            writer.Write("oFracionamento=")
            If (Not (Me._oFracionamento) Is Nothing) Then
                CType(Me._oFracionamento,CodeFluent.Runtime.ICodeFluentObject).Trace(writer)
            Else
                writer.Write("<null>")
            End If
            writer.Write(",")
            writer.Write("_oFracionamentopId=")
            writer.Write(Me._oFracionamentopId)
            writer.Write(",")
            writer.Write("pDataMov=")
            writer.Write(Me.pDataMov)
            writer.Write(",")
            writer.Write("pUsuario=")
            writer.Write(Me.pUsuario)
            writer.Write(",")
            writer.Write("B1_UM=")
            writer.Write(Me.B1_UM)
            writer.Write(",")
            writer.Write("pTara=")
            writer.Write(Me.pTara)
            writer.Write(",")
            writer.Write("pVez=")
            writer.Write(Me.pVez)
            writer.Write(", EntityState=")
            writer.Write(Me.EntityState)
            writer.Write("]")
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Shared Function LoadByEntityKey(ByVal key As String) As S5T.FracionamentoMov
            If (key Is String.Empty) Then
                Return Nothing
            End If
            Dim fracionamentoMov As S5T.FracionamentoMov
            Dim var As Long = CType(ConvertUtilities.ChangeType(key, GetType(Long), -1),Long)
            fracionamentoMov = S5T.FracionamentoMov.Load(var)
            Return fracionamentoMov
        End Function
        
        Protected Overridable Sub ValidateMember(ByVal culture As System.Globalization.CultureInfo, ByVal memberName As String, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException))
        End Sub
        
        Public Overloads Function Clone(ByVal deep As Boolean) As S5T.FracionamentoMov
            Dim fracionamentoMov As S5T.FracionamentoMov = New S5T.FracionamentoMov()
            Me.CopyTo(fracionamentoMov, deep)
            Return fracionamentoMov
        End Function
        
        Public Overloads Function Clone() As S5T.FracionamentoMov
            Dim localClone As S5T.FracionamentoMov = Me.Clone(true)
            Return localClone
        End Function
        
        Function System_ICloneable_Clone() As Object Implements System.ICloneable.Clone
            Dim localClone As Object = Me.Clone
            Return localClone
        End Function
        
        Public Overridable Sub CopyFrom(ByVal dict As System.Collections.IDictionary, ByVal deep As Boolean)
            If (dict Is Nothing) Then
                Throw New System.ArgumentNullException("dict")
            End If
            If (dict.Contains("pId") = true) Then
                Me.pId = CType(ConvertUtilities.ChangeType(dict("pId"), GetType(Long), -1),Long)
            End If
            If (dict.Contains("pUsuario") = true) Then
                Me.pUsuario = CType(ConvertUtilities.ChangeType(dict("pUsuario"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pDataMov") = true) Then
                Me.pDataMov = CType(ConvertUtilities.ChangeType(dict("pDataMov"), GetType(Date), CodeFluentPersistence.DefaultDateTimeValue),Date)
            End If
            If (dict.Contains("pLote") = true) Then
                Me.pLote = CType(ConvertUtilities.ChangeType(dict("pLote"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("pVez") = true) Then
                Me.pVez = CType(ConvertUtilities.ChangeType(dict("pVez"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("pTara") = true) Then
                Me.pTara = CType(ConvertUtilities.ChangeType(dict("pTara"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("B1_UM") = true) Then
                Me.B1_UM = CType(ConvertUtilities.ChangeType(dict("B1_UM"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("G1_QUANT") = true) Then
                Me.G1_QUANT = CType(ConvertUtilities.ChangeType(dict("G1_QUANT"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("B1_DESC") = true) Then
                Me.B1_DESC = CType(ConvertUtilities.ChangeType(dict("B1_DESC"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("G1_COMP") = true) Then
                Me.G1_COMP = CType(ConvertUtilities.ChangeType(dict("G1_COMP"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("G1_ZZQMIN") = true) Then
                Me.G1_ZZQMIN = CType(ConvertUtilities.ChangeType(dict("G1_ZZQMIN"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("pPesoPesado") = true) Then
                Me.pPesoPesado = CType(ConvertUtilities.ChangeType(dict("pPesoPesado"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("G1_ZZQMAX") = true) Then
                Me.G1_ZZQMAX = CType(ConvertUtilities.ChangeType(dict("G1_ZZQMAX"), GetType(Double), CodeFluentPersistence.DefaultDoubleValue),Double)
            End If
            If (dict.Contains("oFracionamentopId") = true) Then
                Me.oFracionamentopId = CType(ConvertUtilities.ChangeType(dict("oFracionamentopId"), GetType(Long), -1),Long)
            End If
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyFrom, false, dict))
        End Sub
        
        Public Overloads Overridable Sub CopyTo(ByVal fracionamentoMov As S5T.FracionamentoMov, ByVal deep As Boolean)
            If (fracionamentoMov Is Nothing) Then
                Throw New System.ArgumentNullException("fracionamentoMov")
            End If
            fracionamentoMov.pId = Me.pId
            fracionamentoMov.pUsuario = Me.pUsuario
            fracionamentoMov.pDataMov = Me.pDataMov
            fracionamentoMov.pLote = Me.pLote
            fracionamentoMov.pVez = Me.pVez
            fracionamentoMov.pTara = Me.pTara
            fracionamentoMov.B1_UM = Me.B1_UM
            fracionamentoMov.G1_QUANT = Me.G1_QUANT
            fracionamentoMov.B1_DESC = Me.B1_DESC
            fracionamentoMov.G1_COMP = Me.G1_COMP
            fracionamentoMov.G1_ZZQMIN = Me.G1_ZZQMIN
            fracionamentoMov.pPesoPesado = Me.pPesoPesado
            fracionamentoMov.G1_ZZQMAX = Me.G1_ZZQMAX
            fracionamentoMov.oFracionamentopId = Me.oFracionamentopId
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, fracionamentoMov))
        End Sub
        
        Public Overloads Overridable Sub CopyTo(ByVal dict As System.Collections.IDictionary, ByVal deep As Boolean)
            If (dict Is Nothing) Then
                Throw New System.ArgumentNullException("dict")
            End If
            dict("pId") = Me.pId
            dict("pUsuario") = Me.pUsuario
            dict("pDataMov") = Me.pDataMov
            dict("pLote") = Me.pLote
            dict("pVez") = Me.pVez
            dict("pTara") = Me.pTara
            dict("B1_UM") = Me.B1_UM
            dict("G1_QUANT") = Me.G1_QUANT
            dict("B1_DESC") = Me.B1_DESC
            dict("G1_COMP") = Me.G1_COMP
            dict("G1_ZZQMIN") = Me.G1_ZZQMIN
            dict("pPesoPesado") = Me.pPesoPesado
            dict("G1_ZZQMAX") = Me.G1_ZZQMAX
            dict("oFracionamentopId") = Me.oFracionamentopId
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, dict))
        End Sub
        
        Protected Sub OnCollectionKeyChanged(ByVal key As Long)
            If (Not (Me.KeyChangedEvent) Is Nothing) Then
                RaiseEvent KeyChanged(Me, New CodeFluent.Runtime.Utilities.KeyChangedEventArgs(Of Long)(key))
            End If
        End Sub
    End Class
End Namespace
