'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CodeFluent.Runtime
Imports CodeFluent.Runtime.Utilities

Namespace S5T
    
    'CodeFluent Entities generated (http://www.softfluent.com). Date: .
    <System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.01234.05678"),  _
     System.SerializableAttribute(),  _
     System.ComponentModel.DataObjectAttribute(),  _
     System.Diagnostics.DebuggerDisplayAttribute("EK={EntityKey}, idtag={idtag}, pId={pId}"),  _
     System.ComponentModel.TypeConverterAttribute(GetType(CodeFluent.Runtime.Design.NameTypeConverter))>  _
    Partial Public Class IndustriaSoroDeQueijoTempoLimpezaAutomatico
        Implements System.ICloneable, System.IComparable, System.IComparable(Of S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico), CodeFluent.Runtime.ICodeFluentCollectionEntity(Of Long), System.ComponentModel.IDataErrorInfo, CodeFluent.Runtime.ICodeFluentMemberValidator, CodeFluent.Runtime.ICodeFluentSummaryValidator, System.IEquatable(Of S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico)
        
        Private _raisePropertyChangedEvents As Boolean = true
        
        Private _entityState As CodeFluent.Runtime.CodeFluentEntityState
        
        Private _pId As Long = -1
        
        Private _idtag As String = CType(Nothing, String)
        
        Private _periodoINI As String = CType(Nothing, String)
        
        Private _periodoFIM As String = CType(Nothing, String)
        
        Private _limpeza_tempo_segundos As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _limpeza_tempo_minutos As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _limpeza_tempo_horas As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _limpeza_tempo_dias As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _limpeza_tempo_dd As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _limpeza_tempo_hh As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _limpeza_tempo_mm As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _limpeza_tempo_ss As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _limpeza_tempo_hhmmss As String = CType(Nothing, String)
        
        Private _limpeza_tempo_datetime As Date = CodeFluentPersistence.DefaultDateTimeValue
        
        Private _automatico_tempo_segundos As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _automatico_tempo_minutos As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _automatico_tempo_horas As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _automatico_tempo_dias As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _automatico_tempo_dd As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _automatico_tempo_hh As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _automatico_tempo_mm As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _automatico_tempo_ss As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _automatico_tempo_hhmmss As String = CType(Nothing, String)
        
        Private _automatico_tempo_datetime As Date = CodeFluentPersistence.DefaultDateTimeValue
        
        Private _ligado_tempo_segundos As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _ligado_tempo_minutos As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _ligado_tempo_horas As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _ligado_tempo_dias As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _ligado_tempo_dd As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _ligado_tempo_hh As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _ligado_tempo_mm As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _ligado_tempo_ss As Integer = CodeFluentPersistence.DefaultInt32Value
        
        Private _ligado_tempo_hhmmss As String = CType(Nothing, String)
        
        Private _ligado_tempo_datetime As Date = CodeFluentPersistence.DefaultDateTimeValue
        
        Public Sub New()
            MyBase.New
            Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created
        End Sub
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Overridable Property RaisePropertyChangedEvents() As Boolean
            Get
                Return Me._raisePropertyChangedEvents
            End Get
            Set
                Me._raisePropertyChangedEvents = value
            End Set
        End Property
        
        Public Overridable Property EntityKey() As String Implements CodeFluent.Runtime.ICodeFluentEntity.EntityKey
            Get
                Return Me.pId.ToString
            End Get
            Set
                Me.pId = CType(ConvertUtilities.ChangeType(value, GetType(Long), -1),Long)
            End Set
        End Property
        
        Public Overridable ReadOnly Property EntityDisplayName() As String Implements CodeFluent.Runtime.ICodeFluentEntity.EntityDisplayName
            Get
                Return Me.idtag
            End Get
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(-1,Long)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Long)),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property pId() As Long
            Get
                Return Me._pId
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of Long).Default.Equals(value, Me._pId) = true) Then
                    Return
                End If
                Dim oldKey As Long = Me._pId
                Me._pId = value
                Try 
                    Me.OnCollectionKeyChanged(oldKey)
                Catch __exception As System.ArgumentException
                    Me._pId = oldKey
                    Return
                End Try
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("pId"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property idtag() As String
            Get
                Return Me._idtag
            End Get
            Set
                Me._idtag = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("idtag"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property periodoINI() As String
            Get
                Return Me._periodoINI
            End Get
            Set
                Me._periodoINI = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("periodoINI"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property periodoFIM() As String
            Get
                Return Me._periodoFIM
            End Get
            Set
                Me._periodoFIM = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("periodoFIM"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property limpeza_tempo_segundos() As Integer
            Get
                Return Me._limpeza_tempo_segundos
            End Get
            Set
                Me._limpeza_tempo_segundos = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("limpeza_tempo_segundos"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property limpeza_tempo_minutos() As Integer
            Get
                Return Me._limpeza_tempo_minutos
            End Get
            Set
                Me._limpeza_tempo_minutos = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("limpeza_tempo_minutos"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property limpeza_tempo_horas() As Integer
            Get
                Return Me._limpeza_tempo_horas
            End Get
            Set
                Me._limpeza_tempo_horas = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("limpeza_tempo_horas"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property limpeza_tempo_dias() As Integer
            Get
                Return Me._limpeza_tempo_dias
            End Get
            Set
                Me._limpeza_tempo_dias = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("limpeza_tempo_dias"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property limpeza_tempo_dd() As Integer
            Get
                Return Me._limpeza_tempo_dd
            End Get
            Set
                Me._limpeza_tempo_dd = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("limpeza_tempo_dd"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property limpeza_tempo_hh() As Integer
            Get
                Return Me._limpeza_tempo_hh
            End Get
            Set
                Me._limpeza_tempo_hh = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("limpeza_tempo_hh"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property limpeza_tempo_mm() As Integer
            Get
                Return Me._limpeza_tempo_mm
            End Get
            Set
                Me._limpeza_tempo_mm = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("limpeza_tempo_mm"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property limpeza_tempo_ss() As Integer
            Get
                Return Me._limpeza_tempo_ss
            End Get
            Set
                Me._limpeza_tempo_ss = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("limpeza_tempo_ss"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property limpeza_tempo_hhmmss() As String
            Get
                Return Me._limpeza_tempo_hhmmss
            End Get
            Set
                Me._limpeza_tempo_hhmmss = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("limpeza_tempo_hhmmss"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Date))>  _
        Public Property limpeza_tempo_datetime() As Date
            Get
                Return Me._limpeza_tempo_datetime
            End Get
            Set
                Me._limpeza_tempo_datetime = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("limpeza_tempo_datetime"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property automatico_tempo_segundos() As Integer
            Get
                Return Me._automatico_tempo_segundos
            End Get
            Set
                Me._automatico_tempo_segundos = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("automatico_tempo_segundos"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property automatico_tempo_minutos() As Integer
            Get
                Return Me._automatico_tempo_minutos
            End Get
            Set
                Me._automatico_tempo_minutos = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("automatico_tempo_minutos"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property automatico_tempo_horas() As Integer
            Get
                Return Me._automatico_tempo_horas
            End Get
            Set
                Me._automatico_tempo_horas = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("automatico_tempo_horas"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property automatico_tempo_dias() As Integer
            Get
                Return Me._automatico_tempo_dias
            End Get
            Set
                Me._automatico_tempo_dias = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("automatico_tempo_dias"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property automatico_tempo_dd() As Integer
            Get
                Return Me._automatico_tempo_dd
            End Get
            Set
                Me._automatico_tempo_dd = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("automatico_tempo_dd"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property automatico_tempo_hh() As Integer
            Get
                Return Me._automatico_tempo_hh
            End Get
            Set
                Me._automatico_tempo_hh = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("automatico_tempo_hh"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property automatico_tempo_mm() As Integer
            Get
                Return Me._automatico_tempo_mm
            End Get
            Set
                Me._automatico_tempo_mm = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("automatico_tempo_mm"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property automatico_tempo_ss() As Integer
            Get
                Return Me._automatico_tempo_ss
            End Get
            Set
                Me._automatico_tempo_ss = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("automatico_tempo_ss"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property automatico_tempo_hhmmss() As String
            Get
                Return Me._automatico_tempo_hhmmss
            End Get
            Set
                Me._automatico_tempo_hhmmss = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("automatico_tempo_hhmmss"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Date))>  _
        Public Property automatico_tempo_datetime() As Date
            Get
                Return Me._automatico_tempo_datetime
            End Get
            Set
                Me._automatico_tempo_datetime = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("automatico_tempo_datetime"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property ligado_tempo_segundos() As Integer
            Get
                Return Me._ligado_tempo_segundos
            End Get
            Set
                Me._ligado_tempo_segundos = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ligado_tempo_segundos"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property ligado_tempo_minutos() As Integer
            Get
                Return Me._ligado_tempo_minutos
            End Get
            Set
                Me._ligado_tempo_minutos = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ligado_tempo_minutos"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property ligado_tempo_horas() As Integer
            Get
                Return Me._ligado_tempo_horas
            End Get
            Set
                Me._ligado_tempo_horas = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ligado_tempo_horas"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property ligado_tempo_dias() As Integer
            Get
                Return Me._ligado_tempo_dias
            End Get
            Set
                Me._ligado_tempo_dias = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ligado_tempo_dias"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property ligado_tempo_dd() As Integer
            Get
                Return Me._ligado_tempo_dd
            End Get
            Set
                Me._ligado_tempo_dd = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ligado_tempo_dd"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property ligado_tempo_hh() As Integer
            Get
                Return Me._ligado_tempo_hh
            End Get
            Set
                Me._ligado_tempo_hh = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ligado_tempo_hh"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property ligado_tempo_mm() As Integer
            Get
                Return Me._ligado_tempo_mm
            End Get
            Set
                Me._ligado_tempo_mm = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ligado_tempo_mm"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultInt32Value),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Integer))>  _
        Public Property ligado_tempo_ss() As Integer
            Get
                Return Me._ligado_tempo_ss
            End Get
            Set
                Me._ligado_tempo_ss = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ligado_tempo_ss"))
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property ligado_tempo_hhmmss() As String
            Get
                Return Me._ligado_tempo_hhmmss
            End Get
            Set
                Me._ligado_tempo_hhmmss = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ligado_tempo_hhmmss"))
            End Set
        End Property
        
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Date))>  _
        Public Property ligado_tempo_datetime() As Date
            Get
                Return Me._ligado_tempo_datetime
            End Get
            Set
                Me._ligado_tempo_datetime = value
                Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("ligado_tempo_datetime"))
            End Set
        End Property
        
        ReadOnly Property System_ComponentModel_IDataErrorInfo_Error() As String Implements System.ComponentModel.IDataErrorInfo.[Error]
            Get
                Return Me.Validate(System.Globalization.CultureInfo.CurrentCulture)
            End Get
        End Property
        
        ReadOnly Property System_ComponentModel_IDataErrorInfo_Item(ByVal columnName As String) As String Implements System.ComponentModel.IDataErrorInfo.Item
            Get
                Return CodeFluentPersistence.ValidateMember(System.Globalization.CultureInfo.CurrentCulture, Me, columnName, Nothing)
            End Get
        End Property
        
        ReadOnly Property CodeFluent_Runtime_Utilities_IKeyable_System_Int64__Key() As Long Implements CodeFluent.Runtime.Utilities.IKeyable(Of Long).Key
            Get
                Return Me.pId
            End Get
        End Property
        
        Public Overridable Property EntityState() As CodeFluent.Runtime.CodeFluentEntityState Implements CodeFluent.Runtime.ICodeFluentEntity.EntityState
            Get
                Return Me._entityState
            End Get
            Set
                If (System.Collections.Generic.EqualityComparer(Of CodeFluent.Runtime.CodeFluentEntityState).Default.Equals(value, Me.EntityState) = true) Then
                    Return
                End If
                If ((Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted)  _
                            AndAlso (value = CodeFluent.Runtime.CodeFluentEntityState.Modified)) Then
                    Return
                End If
                If ((Me._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created)  _
                            AndAlso (value = CodeFluent.Runtime.CodeFluentEntityState.Modified)) Then
                    Return
                End If
                Me._entityState = value
                Me.OnPropertyChanged(New System.ComponentModel.PropertyChangedEventArgs("EntityState"))
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Public Event EntityAction As CodeFluent.Runtime.CodeFluentEntityActionEventHandler Implements CodeFluent.Runtime.ICodeFluentEntity.EntityAction
        
        Public Event KeyChanged As System.EventHandler(Of CodeFluent.Runtime.Utilities.KeyChangedEventArgs(Of Long)) Implements CodeFluent.Runtime.Utilities.IKeyable(Of Long).KeyChanged
        
        Protected Overridable Sub OnPropertyChanged(ByVal e As System.ComponentModel.PropertyChangedEventArgs)
            If (Me.RaisePropertyChangedEvents = false) Then
                Return
            End If
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, e)
            End If
        End Sub
        
        Protected Overridable Sub OnEntityAction(ByVal e As CodeFluent.Runtime.CodeFluentEntityActionEventArgs)
            If (Not (Me.EntityActionEvent) Is Nothing) Then
                RaiseEvent EntityAction(Me, e)
            End If
        End Sub
        
        Public Overloads Overridable Function Equals(ByVal industriaSoroDeQueijoTempoLimpezaAutomatico As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico) As Boolean Implements System.IEquatable(Of S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico).Equals
            If (industriaSoroDeQueijoTempoLimpezaAutomatico Is Nothing) Then
                Return false
            End If
            If (Me.pId = -1) Then
                Return MyBase.Equals(industriaSoroDeQueijoTempoLimpezaAutomatico)
            End If
            Return (Me.pId.Equals(industriaSoroDeQueijoTempoLimpezaAutomatico.pId) = true)
        End Function
        
        Public Overloads Overrides Function GetHashCode() As Integer
            Return Me.pId.GetHashCode
        End Function
        
        Public Overloads Overrides Function Equals(ByVal obj As Object) As Boolean
            Dim industriaSoroDeQueijoTempoLimpezaAutomatico As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico = Nothing
            Try 
                industriaSoroDeQueijoTempoLimpezaAutomatico = CType(obj,S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico)
            Catch icex As System.InvalidCastException
                industriaSoroDeQueijoTempoLimpezaAutomatico = Nothing
            End Try
            Return Me.Equals(industriaSoroDeQueijoTempoLimpezaAutomatico)
        End Function
        
        Overridable Function System_IComparable_CompareTo(ByVal value As Object) As Integer Implements System.IComparable.CompareTo
            Dim industriaSoroDeQueijoTempoLimpezaAutomatico As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico = Nothing
            Try 
                industriaSoroDeQueijoTempoLimpezaAutomatico = CType(value,S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico)
            Catch icex As System.InvalidCastException
                industriaSoroDeQueijoTempoLimpezaAutomatico = Nothing
            End Try
            If (industriaSoroDeQueijoTempoLimpezaAutomatico Is Nothing) Then
                Throw New System.ArgumentException("value")
            End If
            Dim localCompareTo As Integer = Me.CompareTo(industriaSoroDeQueijoTempoLimpezaAutomatico)
            Return localCompareTo
        End Function
        
        Public Overridable Function CompareTo(ByVal industriaSoroDeQueijoTempoLimpezaAutomatico As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico) As Integer Implements System.IComparable(Of S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico).CompareTo
            If (industriaSoroDeQueijoTempoLimpezaAutomatico Is Nothing) Then
                Throw New System.ArgumentNullException("industriaSoroDeQueijoTempoLimpezaAutomatico")
            End If
            Dim localCompareTo As Integer = Me.pId.CompareTo(industriaSoroDeQueijoTempoLimpezaAutomatico.pId)
            Return localCompareTo
        End Function
        
        Public Overloads Overridable Function Validate(ByVal culture As System.Globalization.CultureInfo) As String
            Return CodeFluentPersistence.Validate(culture, Me, Nothing)
        End Function
        
        Public Overloads Overridable Sub Validate(ByVal culture As System.Globalization.CultureInfo, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException)) Implements CodeFluent.Runtime.ICodeFluentSummaryValidator.Validate
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Validating, true, results)
            evt.Culture = culture
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Dim externalValidate As String
                If (Not (evt.Argument) Is Nothing) Then
                    externalValidate = evt.Argument.ToString
                Else
                    externalValidate = S5T.Resources.Manager.GetStringWithDefault(culture, "S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico.ExternalValidate", "Type 'S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico' cannot be validated.", Nothing)
                End If
                CodeFluentPersistence.AddValidationError(results, externalValidate)
            End If
            CodeFluentPersistence.ValidateMember(culture, results, Me, Nothing)
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Validated, false, results))
        End Sub
        
        Public Overloads Sub Validate()
            Dim var As String = Me.Validate(System.Globalization.CultureInfo.CurrentCulture)
            If (Not (var) Is Nothing) Then
                Throw New CodeFluent.Runtime.CodeFluentValidationException(var)
            End If
        End Sub
        
        Function CodeFluent_Runtime_ICodeFluentValidator_Validate(ByVal culture As System.Globalization.CultureInfo) As String Implements CodeFluent.Runtime.ICodeFluentValidator.Validate
            Dim localValidate As String = Me.Validate(culture)
            Return localValidate
        End Function
        
        Sub CodeFluent_Runtime_ICodeFluentMemberValidator_Validate(ByVal culture As System.Globalization.CultureInfo, ByVal memberName As String, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException)) Implements CodeFluent.Runtime.ICodeFluentMemberValidator.Validate
            Me.ValidateMember(culture, memberName, results)
        End Sub
        
        Public Overloads Overridable Function Delete() As Boolean Implements CodeFluent.Runtime.ICodeFluentEntity.Delete
            Dim ret As Boolean = false
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Deleting, true)
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Return ret
            End If
            If (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted) Then
                Return ret
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "IndustriaSoroDeQueijoTempoLimpezaAutomatico", "Delete")
            persistence.AddParameter("@pId", Me.pId, CType(-1,Long))
            persistence.ExecuteNonQuery
            Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Deleted, false, false))
            ret = true
            Return ret
        End Function
        
        Protected Overridable Sub ReadRecord(ByVal reader As System.Data.IDataReader, ByVal options As CodeFluent.Runtime.CodeFluentReloadOptions)
            If (reader Is Nothing) Then
                Throw New System.ArgumentNullException("reader")
            End If
            If (((options And CodeFluent.Runtime.CodeFluentReloadOptions.Properties)  _
                        = 0)  _
                        = false) Then
                Me._pId = CodeFluentPersistence.GetReaderValue(reader, "pId", CType(-1,Long))
                Me._idtag = CodeFluentPersistence.GetReaderValue(reader, "idtag", CType(CType(Nothing, String),String))
                Me._periodoINI = CodeFluentPersistence.GetReaderValue(reader, "periodoINI", CType(CType(Nothing, String),String))
                Me._periodoFIM = CodeFluentPersistence.GetReaderValue(reader, "periodoFIM", CType(CType(Nothing, String),String))
                Me._limpeza_tempo_segundos = CodeFluentPersistence.GetReaderValue(reader, "limpeza_tempo_segundos", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._limpeza_tempo_minutos = CodeFluentPersistence.GetReaderValue(reader, "limpeza_tempo_minutos", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._limpeza_tempo_horas = CodeFluentPersistence.GetReaderValue(reader, "limpeza_tempo_horas", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._limpeza_tempo_dias = CodeFluentPersistence.GetReaderValue(reader, "limpeza_tempo_dias", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._limpeza_tempo_dd = CodeFluentPersistence.GetReaderValue(reader, "limpeza_tempo_dd", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._limpeza_tempo_hh = CodeFluentPersistence.GetReaderValue(reader, "limpeza_tempo_hh", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._limpeza_tempo_mm = CodeFluentPersistence.GetReaderValue(reader, "limpeza_tempo_mm", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._limpeza_tempo_ss = CodeFluentPersistence.GetReaderValue(reader, "limpeza_tempo_ss", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._limpeza_tempo_hhmmss = CodeFluentPersistence.GetReaderValue(reader, "limpeza_tempo_hhmmss", CType(CType(Nothing, String),String))
                Me._limpeza_tempo_datetime = CodeFluentPersistence.GetReaderValue(reader, "limpeza_tempo_datetime", CType(CodeFluentPersistence.DefaultDateTimeValue,Date))
                Me._automatico_tempo_segundos = CodeFluentPersistence.GetReaderValue(reader, "automatico_tempo_segundos", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._automatico_tempo_minutos = CodeFluentPersistence.GetReaderValue(reader, "automatico_tempo_minutos", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._automatico_tempo_horas = CodeFluentPersistence.GetReaderValue(reader, "automatico_tempo_horas", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._automatico_tempo_dias = CodeFluentPersistence.GetReaderValue(reader, "automatico_tempo_dias", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._automatico_tempo_dd = CodeFluentPersistence.GetReaderValue(reader, "automatico_tempo_dd", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._automatico_tempo_hh = CodeFluentPersistence.GetReaderValue(reader, "automatico_tempo_hh", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._automatico_tempo_mm = CodeFluentPersistence.GetReaderValue(reader, "automatico_tempo_mm", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._automatico_tempo_ss = CodeFluentPersistence.GetReaderValue(reader, "automatico_tempo_ss", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._automatico_tempo_hhmmss = CodeFluentPersistence.GetReaderValue(reader, "automatico_tempo_hhmmss", CType(CType(Nothing, String),String))
                Me._automatico_tempo_datetime = CodeFluentPersistence.GetReaderValue(reader, "automatico_tempo_datetime", CType(CodeFluentPersistence.DefaultDateTimeValue,Date))
                Me._ligado_tempo_segundos = CodeFluentPersistence.GetReaderValue(reader, "ligado_tempo_segundos", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._ligado_tempo_minutos = CodeFluentPersistence.GetReaderValue(reader, "ligado_tempo_minutos", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._ligado_tempo_horas = CodeFluentPersistence.GetReaderValue(reader, "ligado_tempo_horas", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._ligado_tempo_dias = CodeFluentPersistence.GetReaderValue(reader, "ligado_tempo_dias", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._ligado_tempo_dd = CodeFluentPersistence.GetReaderValue(reader, "ligado_tempo_dd", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._ligado_tempo_hh = CodeFluentPersistence.GetReaderValue(reader, "ligado_tempo_hh", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._ligado_tempo_mm = CodeFluentPersistence.GetReaderValue(reader, "ligado_tempo_mm", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._ligado_tempo_ss = CodeFluentPersistence.GetReaderValue(reader, "ligado_tempo_ss", CType(CodeFluentPersistence.DefaultInt32Value,Integer))
                Me._ligado_tempo_hhmmss = CodeFluentPersistence.GetReaderValue(reader, "ligado_tempo_hhmmss", CType(CType(Nothing, String),String))
                Me._ligado_tempo_datetime = CodeFluentPersistence.GetReaderValue(reader, "ligado_tempo_datetime", CType(CodeFluentPersistence.DefaultDateTimeValue,Date))
            End If
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecord, false, false))
        End Sub
        
        Sub CodeFluent_Runtime_ICodeFluentEntity_ReadRecord(ByVal reader As System.Data.IDataReader) Implements CodeFluent.Runtime.ICodeFluentEntity.ReadRecord
            Me.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
        End Sub
        
        Protected Overridable Sub ReadRecordOnSave(ByVal reader As System.Data.IDataReader)
            If (reader Is Nothing) Then
                Throw New System.ArgumentNullException("reader")
            End If
            Me._pId = CodeFluentPersistence.GetReaderValue(reader, "pId", CType(-1,Long))
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecordOnSave, false, false))
        End Sub
        
        Sub CodeFluent_Runtime_ICodeFluentEntity_ReadRecordOnSave(ByVal reader As System.Data.IDataReader) Implements CodeFluent.Runtime.ICodeFluentEntity.ReadRecordOnSave
            Me.ReadRecordOnSave(reader)
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Shared Function Load(ByVal pId As Long) As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico
            If (pId = -1) Then
                Return Nothing
            End If
            Dim industriaSoroDeQueijoTempoLimpezaAutomatico As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico = New S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico()
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "IndustriaSoroDeQueijoTempoLimpezaAutomatico", "Load")
            persistence.AddParameter("@pId", pId, CType(-1,Long))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    industriaSoroDeQueijoTempoLimpezaAutomatico.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
                    industriaSoroDeQueijoTempoLimpezaAutomatico.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    Return industriaSoroDeQueijoTempoLimpezaAutomatico
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return Nothing
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], false)>  _
        Public Shared Function LoadBypId(ByVal pId As Long) As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico
            If (pId = -1) Then
                Return Nothing
            End If
            Dim industriaSoroDeQueijoTempoLimpezaAutomatico As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico = New S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico()
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "IndustriaSoroDeQueijoTempoLimpezaAutomatico", "LoadBypId")
            persistence.AddParameter("@pId", pId, CType(-1,Long))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    industriaSoroDeQueijoTempoLimpezaAutomatico.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
                    industriaSoroDeQueijoTempoLimpezaAutomatico.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    Return industriaSoroDeQueijoTempoLimpezaAutomatico
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return Nothing
        End Function
        
        Public Overridable Function Reload(ByVal options As CodeFluent.Runtime.CodeFluentReloadOptions) As Boolean
            Dim ret As Boolean = false
            If (Me.pId = -1) Then
                Return ret
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "IndustriaSoroDeQueijoTempoLimpezaAutomatico", "Load")
            persistence.AddParameter("@pId", Me.pId, CType(-1,Long))
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    Me.ReadRecord(reader, options)
                    Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
                    ret = true
                Else
                    Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted
                End If
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Return ret
        End Function
        
        Protected Overridable Function BaseSave(ByVal force As Boolean) As Boolean
            If (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted) Then
                S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico.Delete(Me)
                Return false
            End If
            Dim evt As CodeFluent.Runtime.CodeFluentEntityActionEventArgs = New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Saving, true)
            Me.OnEntityAction(evt)
            If (evt.Cancel = true) Then
                Return false
            End If
            CodeFluentPersistence.ThrowIfDeleted(Me)
            Me.Validate
            If ((force = false)  _
                        AndAlso (Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged)) Then
                Return false
            End If
            Dim persistence As CodeFluent.Runtime.CodeFluentPersistence = CodeFluentContext.Get(S5T.Constants.S5TStoreName).Persistence
            persistence.CreateStoredProcedureCommand(Nothing, "IndustriaSoroDeQueijoTempoLimpezaAutomatico", "Save")
            persistence.AddParameter("@pId", Me.pId, CType(-1,Long))
            persistence.AddParameter("@idtag", Me.idtag, CType(Nothing, String))
            persistence.AddParameter("@periodoINI", Me.periodoINI, CType(Nothing, String))
            persistence.AddParameter("@periodoFIM", Me.periodoFIM, CType(Nothing, String))
            persistence.AddParameter("@limpeza_tempo_segundos", Me.limpeza_tempo_segundos, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@limpeza_tempo_minutos", Me.limpeza_tempo_minutos, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@limpeza_tempo_horas", Me.limpeza_tempo_horas, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@limpeza_tempo_dias", Me.limpeza_tempo_dias, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@limpeza_tempo_dd", Me.limpeza_tempo_dd, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@limpeza_tempo_hh", Me.limpeza_tempo_hh, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@limpeza_tempo_mm", Me.limpeza_tempo_mm, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@limpeza_tempo_ss", Me.limpeza_tempo_ss, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@limpeza_tempo_hhmmss", Me.limpeza_tempo_hhmmss, CType(Nothing, String))
            persistence.AddParameter("@limpeza_tempo_datetime", Me.limpeza_tempo_datetime, CodeFluentPersistence.DefaultDateTimeValue)
            persistence.AddParameter("@automatico_tempo_segundos", Me.automatico_tempo_segundos, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@automatico_tempo_minutos", Me.automatico_tempo_minutos, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@automatico_tempo_horas", Me.automatico_tempo_horas, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@automatico_tempo_dias", Me.automatico_tempo_dias, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@automatico_tempo_dd", Me.automatico_tempo_dd, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@automatico_tempo_hh", Me.automatico_tempo_hh, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@automatico_tempo_mm", Me.automatico_tempo_mm, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@automatico_tempo_ss", Me.automatico_tempo_ss, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@automatico_tempo_hhmmss", Me.automatico_tempo_hhmmss, CType(Nothing, String))
            persistence.AddParameter("@automatico_tempo_datetime", Me.automatico_tempo_datetime, CodeFluentPersistence.DefaultDateTimeValue)
            persistence.AddParameter("@ligado_tempo_segundos", Me.ligado_tempo_segundos, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@ligado_tempo_minutos", Me.ligado_tempo_minutos, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@ligado_tempo_horas", Me.ligado_tempo_horas, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@ligado_tempo_dias", Me.ligado_tempo_dias, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@ligado_tempo_dd", Me.ligado_tempo_dd, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@ligado_tempo_hh", Me.ligado_tempo_hh, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@ligado_tempo_mm", Me.ligado_tempo_mm, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@ligado_tempo_ss", Me.ligado_tempo_ss, CodeFluentPersistence.DefaultInt32Value)
            persistence.AddParameter("@ligado_tempo_hhmmss", Me.ligado_tempo_hhmmss, CType(Nothing, String))
            persistence.AddParameter("@ligado_tempo_datetime", Me.ligado_tempo_datetime, CodeFluentPersistence.DefaultDateTimeValue)
            persistence.AddParameter("@_trackLastWriteUser", persistence.Context.User.Name)
            Dim reader As System.Data.IDataReader = Nothing
            Try 
                reader = persistence.ExecuteReader
                If (reader.Read = true) Then
                    Me.ReadRecordOnSave(reader)
                End If
                CodeFluentPersistence.NextResults(reader)
            Finally
                If (Not (reader) Is Nothing) Then
                    reader.Dispose
                End If
                persistence.CompleteCommand
            End Try
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.Saved, false, false))
            Me.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged
            Return true
        End Function
        
        Public Overloads Overridable Function Save() As Boolean Implements CodeFluent.Runtime.ICodeFluentEntity.Save
            Dim localSave As Boolean = Me.BaseSave(false)
            Return localSave
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)>  _
        Public Overloads Shared Function Save(ByVal industriaSoroDeQueijoTempoLimpezaAutomatico As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico) As Boolean
            If (industriaSoroDeQueijoTempoLimpezaAutomatico Is Nothing) Then
                Return false
            End If
            Dim ret As Boolean = industriaSoroDeQueijoTempoLimpezaAutomatico.Save
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)>  _
        Public Shared Function Insert(ByVal industriaSoroDeQueijoTempoLimpezaAutomatico As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico) As Boolean
            Dim ret As Boolean = S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico.Save(industriaSoroDeQueijoTempoLimpezaAutomatico)
            Return ret
        End Function
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)>  _
        Public Overloads Shared Function Delete(ByVal industriaSoroDeQueijoTempoLimpezaAutomatico As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico) As Boolean
            If (industriaSoroDeQueijoTempoLimpezaAutomatico Is Nothing) Then
                Return false
            End If
            Dim ret As Boolean = industriaSoroDeQueijoTempoLimpezaAutomatico.Delete
            Return ret
        End Function
        
        Public Function Trace() As String
            Dim stringBuilder As System.Text.StringBuilder = New System.Text.StringBuilder()
            Dim stringWriter As System.IO.StringWriter = New System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture)
            Dim writer As System.CodeDom.Compiler.IndentedTextWriter = New System.CodeDom.Compiler.IndentedTextWriter(stringWriter)
            Me.BaseTrace(writer)
            writer.Flush
            CType(writer,System.IDisposable).Dispose
            CType(stringWriter,System.IDisposable).Dispose
            Dim sr As String = stringBuilder.ToString
            Return sr
        End Function
        
        <System.ComponentModel.BrowsableAttribute(false),  _
         System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)>  _
        Sub CodeFluent_Runtime_ICodeFluentObject_Trace(ByVal writer As System.CodeDom.Compiler.IndentedTextWriter) Implements CodeFluent.Runtime.ICodeFluentObject.Trace
            Me.BaseTrace(writer)
        End Sub
        
        Protected Overridable Sub BaseTrace(ByVal writer As System.CodeDom.Compiler.IndentedTextWriter)
            writer.Write("[")
            writer.Write("pId=")
            writer.Write(Me.pId)
            writer.Write(",")
            writer.Write("idtag=")
            writer.Write(Me.idtag)
            writer.Write(",")
            writer.Write("periodoINI=")
            writer.Write(Me.periodoINI)
            writer.Write(",")
            writer.Write("periodoFIM=")
            writer.Write(Me.periodoFIM)
            writer.Write(",")
            writer.Write("limpeza_tempo_segundos=")
            writer.Write(Me.limpeza_tempo_segundos)
            writer.Write(",")
            writer.Write("limpeza_tempo_minutos=")
            writer.Write(Me.limpeza_tempo_minutos)
            writer.Write(",")
            writer.Write("limpeza_tempo_horas=")
            writer.Write(Me.limpeza_tempo_horas)
            writer.Write(",")
            writer.Write("limpeza_tempo_dias=")
            writer.Write(Me.limpeza_tempo_dias)
            writer.Write(",")
            writer.Write("limpeza_tempo_dd=")
            writer.Write(Me.limpeza_tempo_dd)
            writer.Write(",")
            writer.Write("limpeza_tempo_hh=")
            writer.Write(Me.limpeza_tempo_hh)
            writer.Write(",")
            writer.Write("limpeza_tempo_mm=")
            writer.Write(Me.limpeza_tempo_mm)
            writer.Write(",")
            writer.Write("limpeza_tempo_ss=")
            writer.Write(Me.limpeza_tempo_ss)
            writer.Write(",")
            writer.Write("limpeza_tempo_hhmmss=")
            writer.Write(Me.limpeza_tempo_hhmmss)
            writer.Write(",")
            writer.Write("limpeza_tempo_datetime=")
            writer.Write(Me.limpeza_tempo_datetime)
            writer.Write(",")
            writer.Write("automatico_tempo_segundos=")
            writer.Write(Me.automatico_tempo_segundos)
            writer.Write(",")
            writer.Write("automatico_tempo_minutos=")
            writer.Write(Me.automatico_tempo_minutos)
            writer.Write(",")
            writer.Write("automatico_tempo_horas=")
            writer.Write(Me.automatico_tempo_horas)
            writer.Write(",")
            writer.Write("automatico_tempo_dias=")
            writer.Write(Me.automatico_tempo_dias)
            writer.Write(",")
            writer.Write("automatico_tempo_dd=")
            writer.Write(Me.automatico_tempo_dd)
            writer.Write(",")
            writer.Write("automatico_tempo_hh=")
            writer.Write(Me.automatico_tempo_hh)
            writer.Write(",")
            writer.Write("automatico_tempo_mm=")
            writer.Write(Me.automatico_tempo_mm)
            writer.Write(",")
            writer.Write("automatico_tempo_ss=")
            writer.Write(Me.automatico_tempo_ss)
            writer.Write(",")
            writer.Write("automatico_tempo_hhmmss=")
            writer.Write(Me.automatico_tempo_hhmmss)
            writer.Write(",")
            writer.Write("automatico_tempo_datetime=")
            writer.Write(Me.automatico_tempo_datetime)
            writer.Write(",")
            writer.Write("ligado_tempo_segundos=")
            writer.Write(Me.ligado_tempo_segundos)
            writer.Write(",")
            writer.Write("ligado_tempo_minutos=")
            writer.Write(Me.ligado_tempo_minutos)
            writer.Write(",")
            writer.Write("ligado_tempo_horas=")
            writer.Write(Me.ligado_tempo_horas)
            writer.Write(",")
            writer.Write("ligado_tempo_dias=")
            writer.Write(Me.ligado_tempo_dias)
            writer.Write(",")
            writer.Write("ligado_tempo_dd=")
            writer.Write(Me.ligado_tempo_dd)
            writer.Write(",")
            writer.Write("ligado_tempo_hh=")
            writer.Write(Me.ligado_tempo_hh)
            writer.Write(",")
            writer.Write("ligado_tempo_mm=")
            writer.Write(Me.ligado_tempo_mm)
            writer.Write(",")
            writer.Write("ligado_tempo_ss=")
            writer.Write(Me.ligado_tempo_ss)
            writer.Write(",")
            writer.Write("ligado_tempo_hhmmss=")
            writer.Write(Me.ligado_tempo_hhmmss)
            writer.Write(",")
            writer.Write("ligado_tempo_datetime=")
            writer.Write(Me.ligado_tempo_datetime)
            writer.Write(", EntityState=")
            writer.Write(Me.EntityState)
            writer.Write("]")
        End Sub
        
        <System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Shared Function LoadByEntityKey(ByVal key As String) As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico
            If (key Is String.Empty) Then
                Return Nothing
            End If
            Dim industriaSoroDeQueijoTempoLimpezaAutomatico As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico
            Dim var As Long = CType(ConvertUtilities.ChangeType(key, GetType(Long), -1),Long)
            industriaSoroDeQueijoTempoLimpezaAutomatico = S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico.Load(var)
            Return industriaSoroDeQueijoTempoLimpezaAutomatico
        End Function
        
        Protected Overridable Sub ValidateMember(ByVal culture As System.Globalization.CultureInfo, ByVal memberName As String, ByVal results As System.Collections.Generic.IList(Of CodeFluent.Runtime.CodeFluentValidationException))
        End Sub
        
        Public Overloads Function Clone(ByVal deep As Boolean) As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico
            Dim industriaSoroDeQueijoTempoLimpezaAutomatico As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico = New S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico()
            Me.CopyTo(industriaSoroDeQueijoTempoLimpezaAutomatico, deep)
            Return industriaSoroDeQueijoTempoLimpezaAutomatico
        End Function
        
        Public Overloads Function Clone() As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico
            Dim localClone As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico = Me.Clone(true)
            Return localClone
        End Function
        
        Function System_ICloneable_Clone() As Object Implements System.ICloneable.Clone
            Dim localClone As Object = Me.Clone
            Return localClone
        End Function
        
        Public Overridable Sub CopyFrom(ByVal dict As System.Collections.IDictionary, ByVal deep As Boolean)
            If (dict Is Nothing) Then
                Throw New System.ArgumentNullException("dict")
            End If
            If (dict.Contains("pId") = true) Then
                Me.pId = CType(ConvertUtilities.ChangeType(dict("pId"), GetType(Long), -1),Long)
            End If
            If (dict.Contains("automatico_tempo_datetime") = true) Then
                Me.automatico_tempo_datetime = CType(ConvertUtilities.ChangeType(dict("automatico_tempo_datetime"), GetType(Date), CodeFluentPersistence.DefaultDateTimeValue),Date)
            End If
            If (dict.Contains("automatico_tempo_hhmmss") = true) Then
                Me.automatico_tempo_hhmmss = CType(ConvertUtilities.ChangeType(dict("automatico_tempo_hhmmss"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("ligado_tempo_minutos") = true) Then
                Me.ligado_tempo_minutos = CType(ConvertUtilities.ChangeType(dict("ligado_tempo_minutos"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("ligado_tempo_segundos") = true) Then
                Me.ligado_tempo_segundos = CType(ConvertUtilities.ChangeType(dict("ligado_tempo_segundos"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("automatico_tempo_hh") = true) Then
                Me.automatico_tempo_hh = CType(ConvertUtilities.ChangeType(dict("automatico_tempo_hh"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("automatico_tempo_dd") = true) Then
                Me.automatico_tempo_dd = CType(ConvertUtilities.ChangeType(dict("automatico_tempo_dd"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("automatico_tempo_ss") = true) Then
                Me.automatico_tempo_ss = CType(ConvertUtilities.ChangeType(dict("automatico_tempo_ss"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("automatico_tempo_mm") = true) Then
                Me.automatico_tempo_mm = CType(ConvertUtilities.ChangeType(dict("automatico_tempo_mm"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("ligado_tempo_ss") = true) Then
                Me.ligado_tempo_ss = CType(ConvertUtilities.ChangeType(dict("ligado_tempo_ss"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("ligado_tempo_mm") = true) Then
                Me.ligado_tempo_mm = CType(ConvertUtilities.ChangeType(dict("ligado_tempo_mm"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("ligado_tempo_datetime") = true) Then
                Me.ligado_tempo_datetime = CType(ConvertUtilities.ChangeType(dict("ligado_tempo_datetime"), GetType(Date), CodeFluentPersistence.DefaultDateTimeValue),Date)
            End If
            If (dict.Contains("ligado_tempo_hhmmss") = true) Then
                Me.ligado_tempo_hhmmss = CType(ConvertUtilities.ChangeType(dict("ligado_tempo_hhmmss"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("ligado_tempo_dias") = true) Then
                Me.ligado_tempo_dias = CType(ConvertUtilities.ChangeType(dict("ligado_tempo_dias"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("ligado_tempo_horas") = true) Then
                Me.ligado_tempo_horas = CType(ConvertUtilities.ChangeType(dict("ligado_tempo_horas"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("ligado_tempo_hh") = true) Then
                Me.ligado_tempo_hh = CType(ConvertUtilities.ChangeType(dict("ligado_tempo_hh"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("ligado_tempo_dd") = true) Then
                Me.ligado_tempo_dd = CType(ConvertUtilities.ChangeType(dict("ligado_tempo_dd"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("automatico_tempo_dias") = true) Then
                Me.automatico_tempo_dias = CType(ConvertUtilities.ChangeType(dict("automatico_tempo_dias"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("limpeza_tempo_horas") = true) Then
                Me.limpeza_tempo_horas = CType(ConvertUtilities.ChangeType(dict("limpeza_tempo_horas"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("limpeza_tempo_minutos") = true) Then
                Me.limpeza_tempo_minutos = CType(ConvertUtilities.ChangeType(dict("limpeza_tempo_minutos"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("limpeza_tempo_dd") = true) Then
                Me.limpeza_tempo_dd = CType(ConvertUtilities.ChangeType(dict("limpeza_tempo_dd"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("limpeza_tempo_dias") = true) Then
                Me.limpeza_tempo_dias = CType(ConvertUtilities.ChangeType(dict("limpeza_tempo_dias"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("periodoINI") = true) Then
                Me.periodoINI = CType(ConvertUtilities.ChangeType(dict("periodoINI"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("idtag") = true) Then
                Me.idtag = CType(ConvertUtilities.ChangeType(dict("idtag"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("limpeza_tempo_segundos") = true) Then
                Me.limpeza_tempo_segundos = CType(ConvertUtilities.ChangeType(dict("limpeza_tempo_segundos"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("periodoFIM") = true) Then
                Me.periodoFIM = CType(ConvertUtilities.ChangeType(dict("periodoFIM"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("automatico_tempo_segundos") = true) Then
                Me.automatico_tempo_segundos = CType(ConvertUtilities.ChangeType(dict("automatico_tempo_segundos"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("limpeza_tempo_datetime") = true) Then
                Me.limpeza_tempo_datetime = CType(ConvertUtilities.ChangeType(dict("limpeza_tempo_datetime"), GetType(Date), CodeFluentPersistence.DefaultDateTimeValue),Date)
            End If
            If (dict.Contains("automatico_tempo_horas") = true) Then
                Me.automatico_tempo_horas = CType(ConvertUtilities.ChangeType(dict("automatico_tempo_horas"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("automatico_tempo_minutos") = true) Then
                Me.automatico_tempo_minutos = CType(ConvertUtilities.ChangeType(dict("automatico_tempo_minutos"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("limpeza_tempo_mm") = true) Then
                Me.limpeza_tempo_mm = CType(ConvertUtilities.ChangeType(dict("limpeza_tempo_mm"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("limpeza_tempo_hh") = true) Then
                Me.limpeza_tempo_hh = CType(ConvertUtilities.ChangeType(dict("limpeza_tempo_hh"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            If (dict.Contains("limpeza_tempo_hhmmss") = true) Then
                Me.limpeza_tempo_hhmmss = CType(ConvertUtilities.ChangeType(dict("limpeza_tempo_hhmmss"), GetType(String), CType(Nothing, String)),String)
            End If
            If (dict.Contains("limpeza_tempo_ss") = true) Then
                Me.limpeza_tempo_ss = CType(ConvertUtilities.ChangeType(dict("limpeza_tempo_ss"), GetType(Integer), CodeFluentPersistence.DefaultInt32Value),Integer)
            End If
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyFrom, false, dict))
        End Sub
        
        Public Overloads Overridable Sub CopyTo(ByVal industriaSoroDeQueijoTempoLimpezaAutomatico As S5T.IndustriaSoroDeQueijoTempoLimpezaAutomatico, ByVal deep As Boolean)
            If (industriaSoroDeQueijoTempoLimpezaAutomatico Is Nothing) Then
                Throw New System.ArgumentNullException("industriaSoroDeQueijoTempoLimpezaAutomatico")
            End If
            industriaSoroDeQueijoTempoLimpezaAutomatico.pId = Me.pId
            industriaSoroDeQueijoTempoLimpezaAutomatico.automatico_tempo_datetime = Me.automatico_tempo_datetime
            industriaSoroDeQueijoTempoLimpezaAutomatico.automatico_tempo_hhmmss = Me.automatico_tempo_hhmmss
            industriaSoroDeQueijoTempoLimpezaAutomatico.ligado_tempo_minutos = Me.ligado_tempo_minutos
            industriaSoroDeQueijoTempoLimpezaAutomatico.ligado_tempo_segundos = Me.ligado_tempo_segundos
            industriaSoroDeQueijoTempoLimpezaAutomatico.automatico_tempo_hh = Me.automatico_tempo_hh
            industriaSoroDeQueijoTempoLimpezaAutomatico.automatico_tempo_dd = Me.automatico_tempo_dd
            industriaSoroDeQueijoTempoLimpezaAutomatico.automatico_tempo_ss = Me.automatico_tempo_ss
            industriaSoroDeQueijoTempoLimpezaAutomatico.automatico_tempo_mm = Me.automatico_tempo_mm
            industriaSoroDeQueijoTempoLimpezaAutomatico.ligado_tempo_ss = Me.ligado_tempo_ss
            industriaSoroDeQueijoTempoLimpezaAutomatico.ligado_tempo_mm = Me.ligado_tempo_mm
            industriaSoroDeQueijoTempoLimpezaAutomatico.ligado_tempo_datetime = Me.ligado_tempo_datetime
            industriaSoroDeQueijoTempoLimpezaAutomatico.ligado_tempo_hhmmss = Me.ligado_tempo_hhmmss
            industriaSoroDeQueijoTempoLimpezaAutomatico.ligado_tempo_dias = Me.ligado_tempo_dias
            industriaSoroDeQueijoTempoLimpezaAutomatico.ligado_tempo_horas = Me.ligado_tempo_horas
            industriaSoroDeQueijoTempoLimpezaAutomatico.ligado_tempo_hh = Me.ligado_tempo_hh
            industriaSoroDeQueijoTempoLimpezaAutomatico.ligado_tempo_dd = Me.ligado_tempo_dd
            industriaSoroDeQueijoTempoLimpezaAutomatico.automatico_tempo_dias = Me.automatico_tempo_dias
            industriaSoroDeQueijoTempoLimpezaAutomatico.limpeza_tempo_horas = Me.limpeza_tempo_horas
            industriaSoroDeQueijoTempoLimpezaAutomatico.limpeza_tempo_minutos = Me.limpeza_tempo_minutos
            industriaSoroDeQueijoTempoLimpezaAutomatico.limpeza_tempo_dd = Me.limpeza_tempo_dd
            industriaSoroDeQueijoTempoLimpezaAutomatico.limpeza_tempo_dias = Me.limpeza_tempo_dias
            industriaSoroDeQueijoTempoLimpezaAutomatico.periodoINI = Me.periodoINI
            industriaSoroDeQueijoTempoLimpezaAutomatico.idtag = Me.idtag
            industriaSoroDeQueijoTempoLimpezaAutomatico.limpeza_tempo_segundos = Me.limpeza_tempo_segundos
            industriaSoroDeQueijoTempoLimpezaAutomatico.periodoFIM = Me.periodoFIM
            industriaSoroDeQueijoTempoLimpezaAutomatico.automatico_tempo_segundos = Me.automatico_tempo_segundos
            industriaSoroDeQueijoTempoLimpezaAutomatico.limpeza_tempo_datetime = Me.limpeza_tempo_datetime
            industriaSoroDeQueijoTempoLimpezaAutomatico.automatico_tempo_horas = Me.automatico_tempo_horas
            industriaSoroDeQueijoTempoLimpezaAutomatico.automatico_tempo_minutos = Me.automatico_tempo_minutos
            industriaSoroDeQueijoTempoLimpezaAutomatico.limpeza_tempo_mm = Me.limpeza_tempo_mm
            industriaSoroDeQueijoTempoLimpezaAutomatico.limpeza_tempo_hh = Me.limpeza_tempo_hh
            industriaSoroDeQueijoTempoLimpezaAutomatico.limpeza_tempo_hhmmss = Me.limpeza_tempo_hhmmss
            industriaSoroDeQueijoTempoLimpezaAutomatico.limpeza_tempo_ss = Me.limpeza_tempo_ss
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, industriaSoroDeQueijoTempoLimpezaAutomatico))
        End Sub
        
        Public Overloads Overridable Sub CopyTo(ByVal dict As System.Collections.IDictionary, ByVal deep As Boolean)
            If (dict Is Nothing) Then
                Throw New System.ArgumentNullException("dict")
            End If
            dict("pId") = Me.pId
            dict("automatico_tempo_datetime") = Me.automatico_tempo_datetime
            dict("automatico_tempo_hhmmss") = Me.automatico_tempo_hhmmss
            dict("ligado_tempo_minutos") = Me.ligado_tempo_minutos
            dict("ligado_tempo_segundos") = Me.ligado_tempo_segundos
            dict("automatico_tempo_hh") = Me.automatico_tempo_hh
            dict("automatico_tempo_dd") = Me.automatico_tempo_dd
            dict("automatico_tempo_ss") = Me.automatico_tempo_ss
            dict("automatico_tempo_mm") = Me.automatico_tempo_mm
            dict("ligado_tempo_ss") = Me.ligado_tempo_ss
            dict("ligado_tempo_mm") = Me.ligado_tempo_mm
            dict("ligado_tempo_datetime") = Me.ligado_tempo_datetime
            dict("ligado_tempo_hhmmss") = Me.ligado_tempo_hhmmss
            dict("ligado_tempo_dias") = Me.ligado_tempo_dias
            dict("ligado_tempo_horas") = Me.ligado_tempo_horas
            dict("ligado_tempo_hh") = Me.ligado_tempo_hh
            dict("ligado_tempo_dd") = Me.ligado_tempo_dd
            dict("automatico_tempo_dias") = Me.automatico_tempo_dias
            dict("limpeza_tempo_horas") = Me.limpeza_tempo_horas
            dict("limpeza_tempo_minutos") = Me.limpeza_tempo_minutos
            dict("limpeza_tempo_dd") = Me.limpeza_tempo_dd
            dict("limpeza_tempo_dias") = Me.limpeza_tempo_dias
            dict("periodoINI") = Me.periodoINI
            dict("idtag") = Me.idtag
            dict("limpeza_tempo_segundos") = Me.limpeza_tempo_segundos
            dict("periodoFIM") = Me.periodoFIM
            dict("automatico_tempo_segundos") = Me.automatico_tempo_segundos
            dict("limpeza_tempo_datetime") = Me.limpeza_tempo_datetime
            dict("automatico_tempo_horas") = Me.automatico_tempo_horas
            dict("automatico_tempo_minutos") = Me.automatico_tempo_minutos
            dict("limpeza_tempo_mm") = Me.limpeza_tempo_mm
            dict("limpeza_tempo_hh") = Me.limpeza_tempo_hh
            dict("limpeza_tempo_hhmmss") = Me.limpeza_tempo_hhmmss
            dict("limpeza_tempo_ss") = Me.limpeza_tempo_ss
            Me.OnEntityAction(New CodeFluent.Runtime.CodeFluentEntityActionEventArgs(Me, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, dict))
        End Sub
        
        Protected Sub OnCollectionKeyChanged(ByVal key As Long)
            If (Not (Me.KeyChangedEvent) Is Nothing) Then
                RaiseEvent KeyChanged(Me, New CodeFluent.Runtime.Utilities.KeyChangedEventArgs(Of Long)(key))
            End If
        End Sub
    End Class
End Namespace
