'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CodeFluent.Runtime
Imports CodeFluent.Runtime.Utilities

Namespace S5T
    
    'CodeFluent Entities generated (http://www.softfluent.com). Date: .
    <System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.01234.05678"),  _
     System.SerializableAttribute(),  _
     System.ComponentModel.DataObjectAttribute()>  _
    Partial Public Class TaraFracionamentoView
        Implements CodeFluent.Runtime.ICodeFluentLightEntity
        
        Private _pId As Long = -1
        
        Private _c2_PRODUTO As String = CType(Nothing, String)
        
        Private _g1_COMP As String = CType(Nothing, String)
        
        Private _pTara As String = CType(Nothing, String)
        
        Private _b1_DESC_PROD As String = CType(Nothing, String)
        
        Private _b1_DESC As String = CType(Nothing, String)
        
        Private _pEmbalagemDescricao As String = CType(Nothing, String)
        
        Private _pEmbalagemPeso As Double = CodeFluentPersistence.DefaultDoubleValue
        
        Public Sub New()
            MyBase.New
        End Sub
        
        <System.ComponentModel.DefaultValueAttribute(CType(-1,Long)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Long)),  _
         System.ComponentModel.DataObjectFieldAttribute(true)>  _
        Public Property pId() As Long
            Get
                Return Me._pId
            End Get
            Set
                Me._pId = value
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property C2_PRODUTO() As String
            Get
                Return Me._c2_PRODUTO
            End Get
            Set
                Me._c2_PRODUTO = value
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property G1_COMP() As String
            Get
                Return Me._g1_COMP
            End Get
            Set
                Me._g1_COMP = value
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pTara() As String
            Get
                Return Me._pTara
            End Get
            Set
                Me._pTara = value
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property B1_DESC_PROD() As String
            Get
                Return Me._b1_DESC_PROD
            End Get
            Set
                Me._b1_DESC_PROD = value
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property B1_DESC() As String
            Get
                Return Me._b1_DESC
            End Get
            Set
                Me._b1_DESC = value
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CType(Nothing, String)),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Type:=GetType(String))>  _
        Public Property pEmbalagemDescricao() As String
            Get
                Return Me._pEmbalagemDescricao
            End Get
            Set
                Me._pEmbalagemDescricao = value
            End Set
        End Property
        
        <System.ComponentModel.DefaultValueAttribute(CodeFluentPersistence.DefaultDoubleValue),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=false, Type:=GetType(Double))>  _
        Public Property pEmbalagemPeso() As Double
            Get
                Return Me._pEmbalagemPeso
            End Get
            Set
                Me._pEmbalagemPeso = value
            End Set
        End Property
        
        Protected Overridable Sub ReadRecord(ByVal reader As System.Data.IDataReader, ByVal options As CodeFluent.Runtime.CodeFluentReloadOptions)
            If (reader Is Nothing) Then
                Throw New System.ArgumentNullException("reader")
            End If
            If (((options And CodeFluent.Runtime.CodeFluentReloadOptions.Properties)  _
                        = 0)  _
                        = false) Then
                Me._pId = CodeFluentPersistence.GetReaderValue(reader, "pId", CType(-1,Long))
                Me._c2_PRODUTO = CodeFluentPersistence.GetReaderValue(reader, "C2_PRODUTO", CType(CType(Nothing, String),String))
                Me._g1_COMP = CodeFluentPersistence.GetReaderValue(reader, "G1_COMP", CType(CType(Nothing, String),String))
                Me._pTara = CodeFluentPersistence.GetReaderValue(reader, "pTara", CType(CType(Nothing, String),String))
                Me._b1_DESC_PROD = CodeFluentPersistence.GetReaderValue(reader, "B1_DESC_PROD", CType(CType(Nothing, String),String))
                Me._b1_DESC = CodeFluentPersistence.GetReaderValue(reader, "B1_DESC", CType(CType(Nothing, String),String))
                Me._pEmbalagemDescricao = CodeFluentPersistence.GetReaderValue(reader, "pEmbalagemDescricao", CType(CType(Nothing, String),String))
                Me._pEmbalagemPeso = CodeFluentPersistence.GetReaderValue(reader, "pEmbalagemPeso", CType(CodeFluentPersistence.DefaultDoubleValue,Double))
            End If
        End Sub
        
        Sub CodeFluent_Runtime_ICodeFluentLightEntity_ReadRecord(ByVal reader As System.Data.IDataReader) Implements CodeFluent.Runtime.ICodeFluentLightEntity.ReadRecord
            Me.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.[Default])
        End Sub
    End Class
End Namespace
