<?xml version="1.0" encoding="utf-8"?><Database Name="s5taviacao" Class="DataClassesCadastroVisitanteDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.50.39;Initial Catalog=s5taviacao;Persist Security Info=True;User ID=4t" SettingsObjectName="S5TWebCam.Settings" SettingsPropertyName="s5taviacaoConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VisitanteVisita" Member="VisitanteVisitas">
    <Type Name="VisitanteVisita">
      <Column Name="pId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pNome" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </Type>
  </Table>
</Database>